// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SpellProto.proto

package com.lvl6.aoc2.proto;

public final class Spell {
  private Spell() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface SpellProtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional int32 spellID = 1;
    boolean hasSpellID();
    int getSpellID();
    
    // required .com.lvl6.aoc2.proto.ClassType classType = 2;
    boolean hasClassType();
    com.lvl6.aoc2.proto.ClassEnum.ClassType getClassType();
    
    // optional string name = 3;
    boolean hasName();
    String getName();
    
    // optional .com.lvl6.aoc2.proto.SpellProto.FunctionType function = 4;
    boolean hasFunction();
    com.lvl6.aoc2.proto.Spell.SpellProto.FunctionType getFunction();
    
    // optional int32 strength = 5;
    boolean hasStrength();
    int getStrength();
    
    // optional int32 manaCost = 6;
    boolean hasManaCost();
    int getManaCost();
    
    // optional int32 duration = 7;
    boolean hasDuration();
    int getDuration();
    
    // optional int32 speed = 8;
    boolean hasSpeed();
    int getSpeed();
    
    // optional bool targetted = 9;
    boolean hasTargetted();
    boolean getTargetted();
    
    // optional float size = 10;
    boolean hasSize();
    float getSize();
    
    // optional float castTime = 11;
    boolean hasCastTime();
    float getCastTime();
    
    // optional float coolDown = 12;
    boolean hasCoolDown();
    float getCoolDown();
    
    // optional float range = 13;
    boolean hasRange();
    float getRange();
    
    // optional int32 levelReq = 14;
    boolean hasLevelReq();
    int getLevelReq();
    
    // optional int32 spellLvl = 15;
    boolean hasSpellLvl();
    int getSpellLvl();
    
    // optional int32 researchCost = 16;
    boolean hasResearchCost();
    int getResearchCost();
    
    // optional int32 researchTime = 17;
    boolean hasResearchTime();
    int getResearchTime();
    
    // required .com.lvl6.aoc2.proto.ResourceType researchResource = 18;
    boolean hasResearchResource();
    com.lvl6.aoc2.proto.ResourceEnum.ResourceType getResearchResource();
  }
  public static final class SpellProto extends
      com.google.protobuf.GeneratedMessage
      implements SpellProtoOrBuilder {
    // Use SpellProto.newBuilder() to construct.
    private SpellProto(Builder builder) {
      super(builder);
    }
    private SpellProto(boolean noInit) {}
    
    private static final SpellProto defaultInstance;
    public static SpellProto getDefaultInstance() {
      return defaultInstance;
    }
    
    public SpellProto getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lvl6.aoc2.proto.Spell.internal_static_com_lvl6_aoc2_proto_SpellProto_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lvl6.aoc2.proto.Spell.internal_static_com_lvl6_aoc2_proto_SpellProto_fieldAccessorTable;
    }
    
    public enum FunctionType
        implements com.google.protobuf.ProtocolMessageEnum {
      ATTACK(0, 0),
      FLAT_BUFF(1, 1),
      SCALE_BUFF(2, 2),
      HEAL_SELF(3, 3),
      HEAL_OTHER(4, 4),
      ;
      
      public static final int ATTACK_VALUE = 0;
      public static final int FLAT_BUFF_VALUE = 1;
      public static final int SCALE_BUFF_VALUE = 2;
      public static final int HEAL_SELF_VALUE = 3;
      public static final int HEAL_OTHER_VALUE = 4;
      
      
      public final int getNumber() { return value; }
      
      public static FunctionType valueOf(int value) {
        switch (value) {
          case 0: return ATTACK;
          case 1: return FLAT_BUFF;
          case 2: return SCALE_BUFF;
          case 3: return HEAL_SELF;
          case 4: return HEAL_OTHER;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<FunctionType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<FunctionType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<FunctionType>() {
              public FunctionType findValueByNumber(int number) {
                return FunctionType.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.lvl6.aoc2.proto.Spell.SpellProto.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final FunctionType[] VALUES = {
        ATTACK, FLAT_BUFF, SCALE_BUFF, HEAL_SELF, HEAL_OTHER, 
      };
      
      public static FunctionType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private FunctionType(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:com.lvl6.aoc2.proto.SpellProto.FunctionType)
    }
    
    private int bitField0_;
    // optional int32 spellID = 1;
    public static final int SPELLID_FIELD_NUMBER = 1;
    private int spellID_;
    public boolean hasSpellID() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getSpellID() {
      return spellID_;
    }
    
    // required .com.lvl6.aoc2.proto.ClassType classType = 2;
    public static final int CLASSTYPE_FIELD_NUMBER = 2;
    private com.lvl6.aoc2.proto.ClassEnum.ClassType classType_;
    public boolean hasClassType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public com.lvl6.aoc2.proto.ClassEnum.ClassType getClassType() {
      return classType_;
    }
    
    // optional string name = 3;
    public static final int NAME_FIELD_NUMBER = 3;
    private java.lang.Object name_;
    public boolean hasName() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          name_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional .com.lvl6.aoc2.proto.SpellProto.FunctionType function = 4;
    public static final int FUNCTION_FIELD_NUMBER = 4;
    private com.lvl6.aoc2.proto.Spell.SpellProto.FunctionType function_;
    public boolean hasFunction() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public com.lvl6.aoc2.proto.Spell.SpellProto.FunctionType getFunction() {
      return function_;
    }
    
    // optional int32 strength = 5;
    public static final int STRENGTH_FIELD_NUMBER = 5;
    private int strength_;
    public boolean hasStrength() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public int getStrength() {
      return strength_;
    }
    
    // optional int32 manaCost = 6;
    public static final int MANACOST_FIELD_NUMBER = 6;
    private int manaCost_;
    public boolean hasManaCost() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public int getManaCost() {
      return manaCost_;
    }
    
    // optional int32 duration = 7;
    public static final int DURATION_FIELD_NUMBER = 7;
    private int duration_;
    public boolean hasDuration() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public int getDuration() {
      return duration_;
    }
    
    // optional int32 speed = 8;
    public static final int SPEED_FIELD_NUMBER = 8;
    private int speed_;
    public boolean hasSpeed() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    public int getSpeed() {
      return speed_;
    }
    
    // optional bool targetted = 9;
    public static final int TARGETTED_FIELD_NUMBER = 9;
    private boolean targetted_;
    public boolean hasTargetted() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    public boolean getTargetted() {
      return targetted_;
    }
    
    // optional float size = 10;
    public static final int SIZE_FIELD_NUMBER = 10;
    private float size_;
    public boolean hasSize() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    public float getSize() {
      return size_;
    }
    
    // optional float castTime = 11;
    public static final int CASTTIME_FIELD_NUMBER = 11;
    private float castTime_;
    public boolean hasCastTime() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    public float getCastTime() {
      return castTime_;
    }
    
    // optional float coolDown = 12;
    public static final int COOLDOWN_FIELD_NUMBER = 12;
    private float coolDown_;
    public boolean hasCoolDown() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    public float getCoolDown() {
      return coolDown_;
    }
    
    // optional float range = 13;
    public static final int RANGE_FIELD_NUMBER = 13;
    private float range_;
    public boolean hasRange() {
      return ((bitField0_ & 0x00001000) == 0x00001000);
    }
    public float getRange() {
      return range_;
    }
    
    // optional int32 levelReq = 14;
    public static final int LEVELREQ_FIELD_NUMBER = 14;
    private int levelReq_;
    public boolean hasLevelReq() {
      return ((bitField0_ & 0x00002000) == 0x00002000);
    }
    public int getLevelReq() {
      return levelReq_;
    }
    
    // optional int32 spellLvl = 15;
    public static final int SPELLLVL_FIELD_NUMBER = 15;
    private int spellLvl_;
    public boolean hasSpellLvl() {
      return ((bitField0_ & 0x00004000) == 0x00004000);
    }
    public int getSpellLvl() {
      return spellLvl_;
    }
    
    // optional int32 researchCost = 16;
    public static final int RESEARCHCOST_FIELD_NUMBER = 16;
    private int researchCost_;
    public boolean hasResearchCost() {
      return ((bitField0_ & 0x00008000) == 0x00008000);
    }
    public int getResearchCost() {
      return researchCost_;
    }
    
    // optional int32 researchTime = 17;
    public static final int RESEARCHTIME_FIELD_NUMBER = 17;
    private int researchTime_;
    public boolean hasResearchTime() {
      return ((bitField0_ & 0x00010000) == 0x00010000);
    }
    public int getResearchTime() {
      return researchTime_;
    }
    
    // required .com.lvl6.aoc2.proto.ResourceType researchResource = 18;
    public static final int RESEARCHRESOURCE_FIELD_NUMBER = 18;
    private com.lvl6.aoc2.proto.ResourceEnum.ResourceType researchResource_;
    public boolean hasResearchResource() {
      return ((bitField0_ & 0x00020000) == 0x00020000);
    }
    public com.lvl6.aoc2.proto.ResourceEnum.ResourceType getResearchResource() {
      return researchResource_;
    }
    
    private void initFields() {
      spellID_ = 0;
      classType_ = com.lvl6.aoc2.proto.ClassEnum.ClassType.WARRIOR;
      name_ = "";
      function_ = com.lvl6.aoc2.proto.Spell.SpellProto.FunctionType.ATTACK;
      strength_ = 0;
      manaCost_ = 0;
      duration_ = 0;
      speed_ = 0;
      targetted_ = false;
      size_ = 0F;
      castTime_ = 0F;
      coolDown_ = 0F;
      range_ = 0F;
      levelReq_ = 0;
      spellLvl_ = 0;
      researchCost_ = 0;
      researchTime_ = 0;
      researchResource_ = com.lvl6.aoc2.proto.ResourceEnum.ResourceType.GOLD;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasClassType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasResearchResource()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, spellID_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, classType_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeEnum(4, function_.getNumber());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, strength_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(6, manaCost_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt32(7, duration_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeInt32(8, speed_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeBool(9, targetted_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeFloat(10, size_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeFloat(11, castTime_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeFloat(12, coolDown_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        output.writeFloat(13, range_);
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        output.writeInt32(14, levelReq_);
      }
      if (((bitField0_ & 0x00004000) == 0x00004000)) {
        output.writeInt32(15, spellLvl_);
      }
      if (((bitField0_ & 0x00008000) == 0x00008000)) {
        output.writeInt32(16, researchCost_);
      }
      if (((bitField0_ & 0x00010000) == 0x00010000)) {
        output.writeInt32(17, researchTime_);
      }
      if (((bitField0_ & 0x00020000) == 0x00020000)) {
        output.writeEnum(18, researchResource_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, spellID_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, classType_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, function_.getNumber());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, strength_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, manaCost_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, duration_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, speed_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(9, targetted_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(10, size_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(11, castTime_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(12, coolDown_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(13, range_);
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(14, levelReq_);
      }
      if (((bitField0_ & 0x00004000) == 0x00004000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(15, spellLvl_);
      }
      if (((bitField0_ & 0x00008000) == 0x00008000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(16, researchCost_);
      }
      if (((bitField0_ & 0x00010000) == 0x00010000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(17, researchTime_);
      }
      if (((bitField0_ & 0x00020000) == 0x00020000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(18, researchResource_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.lvl6.aoc2.proto.Spell.SpellProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.lvl6.aoc2.proto.Spell.SpellProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.lvl6.aoc2.proto.Spell.SpellProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.lvl6.aoc2.proto.Spell.SpellProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.lvl6.aoc2.proto.Spell.SpellProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.lvl6.aoc2.proto.Spell.SpellProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.lvl6.aoc2.proto.Spell.SpellProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.lvl6.aoc2.proto.Spell.SpellProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.lvl6.aoc2.proto.Spell.SpellProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.lvl6.aoc2.proto.Spell.SpellProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.lvl6.aoc2.proto.Spell.SpellProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.lvl6.aoc2.proto.Spell.SpellProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.lvl6.aoc2.proto.Spell.internal_static_com_lvl6_aoc2_proto_SpellProto_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.lvl6.aoc2.proto.Spell.internal_static_com_lvl6_aoc2_proto_SpellProto_fieldAccessorTable;
      }
      
      // Construct using com.lvl6.aoc2.proto.Spell.SpellProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        spellID_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        classType_ = com.lvl6.aoc2.proto.ClassEnum.ClassType.WARRIOR;
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        function_ = com.lvl6.aoc2.proto.Spell.SpellProto.FunctionType.ATTACK;
        bitField0_ = (bitField0_ & ~0x00000008);
        strength_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        manaCost_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        duration_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        speed_ = 0;
        bitField0_ = (bitField0_ & ~0x00000080);
        targetted_ = false;
        bitField0_ = (bitField0_ & ~0x00000100);
        size_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000200);
        castTime_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000400);
        coolDown_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000800);
        range_ = 0F;
        bitField0_ = (bitField0_ & ~0x00001000);
        levelReq_ = 0;
        bitField0_ = (bitField0_ & ~0x00002000);
        spellLvl_ = 0;
        bitField0_ = (bitField0_ & ~0x00004000);
        researchCost_ = 0;
        bitField0_ = (bitField0_ & ~0x00008000);
        researchTime_ = 0;
        bitField0_ = (bitField0_ & ~0x00010000);
        researchResource_ = com.lvl6.aoc2.proto.ResourceEnum.ResourceType.GOLD;
        bitField0_ = (bitField0_ & ~0x00020000);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.lvl6.aoc2.proto.Spell.SpellProto.getDescriptor();
      }
      
      public com.lvl6.aoc2.proto.Spell.SpellProto getDefaultInstanceForType() {
        return com.lvl6.aoc2.proto.Spell.SpellProto.getDefaultInstance();
      }
      
      public com.lvl6.aoc2.proto.Spell.SpellProto build() {
        com.lvl6.aoc2.proto.Spell.SpellProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.lvl6.aoc2.proto.Spell.SpellProto buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.lvl6.aoc2.proto.Spell.SpellProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.lvl6.aoc2.proto.Spell.SpellProto buildPartial() {
        com.lvl6.aoc2.proto.Spell.SpellProto result = new com.lvl6.aoc2.proto.Spell.SpellProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.spellID_ = spellID_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.classType_ = classType_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.function_ = function_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.strength_ = strength_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.manaCost_ = manaCost_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.duration_ = duration_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.speed_ = speed_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.targetted_ = targetted_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.size_ = size_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.castTime_ = castTime_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000800;
        }
        result.coolDown_ = coolDown_;
        if (((from_bitField0_ & 0x00001000) == 0x00001000)) {
          to_bitField0_ |= 0x00001000;
        }
        result.range_ = range_;
        if (((from_bitField0_ & 0x00002000) == 0x00002000)) {
          to_bitField0_ |= 0x00002000;
        }
        result.levelReq_ = levelReq_;
        if (((from_bitField0_ & 0x00004000) == 0x00004000)) {
          to_bitField0_ |= 0x00004000;
        }
        result.spellLvl_ = spellLvl_;
        if (((from_bitField0_ & 0x00008000) == 0x00008000)) {
          to_bitField0_ |= 0x00008000;
        }
        result.researchCost_ = researchCost_;
        if (((from_bitField0_ & 0x00010000) == 0x00010000)) {
          to_bitField0_ |= 0x00010000;
        }
        result.researchTime_ = researchTime_;
        if (((from_bitField0_ & 0x00020000) == 0x00020000)) {
          to_bitField0_ |= 0x00020000;
        }
        result.researchResource_ = researchResource_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.lvl6.aoc2.proto.Spell.SpellProto) {
          return mergeFrom((com.lvl6.aoc2.proto.Spell.SpellProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.lvl6.aoc2.proto.Spell.SpellProto other) {
        if (other == com.lvl6.aoc2.proto.Spell.SpellProto.getDefaultInstance()) return this;
        if (other.hasSpellID()) {
          setSpellID(other.getSpellID());
        }
        if (other.hasClassType()) {
          setClassType(other.getClassType());
        }
        if (other.hasName()) {
          setName(other.getName());
        }
        if (other.hasFunction()) {
          setFunction(other.getFunction());
        }
        if (other.hasStrength()) {
          setStrength(other.getStrength());
        }
        if (other.hasManaCost()) {
          setManaCost(other.getManaCost());
        }
        if (other.hasDuration()) {
          setDuration(other.getDuration());
        }
        if (other.hasSpeed()) {
          setSpeed(other.getSpeed());
        }
        if (other.hasTargetted()) {
          setTargetted(other.getTargetted());
        }
        if (other.hasSize()) {
          setSize(other.getSize());
        }
        if (other.hasCastTime()) {
          setCastTime(other.getCastTime());
        }
        if (other.hasCoolDown()) {
          setCoolDown(other.getCoolDown());
        }
        if (other.hasRange()) {
          setRange(other.getRange());
        }
        if (other.hasLevelReq()) {
          setLevelReq(other.getLevelReq());
        }
        if (other.hasSpellLvl()) {
          setSpellLvl(other.getSpellLvl());
        }
        if (other.hasResearchCost()) {
          setResearchCost(other.getResearchCost());
        }
        if (other.hasResearchTime()) {
          setResearchTime(other.getResearchTime());
        }
        if (other.hasResearchResource()) {
          setResearchResource(other.getResearchResource());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasClassType()) {
          
          return false;
        }
        if (!hasResearchResource()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              spellID_ = input.readInt32();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              com.lvl6.aoc2.proto.ClassEnum.ClassType value = com.lvl6.aoc2.proto.ClassEnum.ClassType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                classType_ = value;
              }
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              name_ = input.readBytes();
              break;
            }
            case 32: {
              int rawValue = input.readEnum();
              com.lvl6.aoc2.proto.Spell.SpellProto.FunctionType value = com.lvl6.aoc2.proto.Spell.SpellProto.FunctionType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(4, rawValue);
              } else {
                bitField0_ |= 0x00000008;
                function_ = value;
              }
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              strength_ = input.readInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              manaCost_ = input.readInt32();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              duration_ = input.readInt32();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              speed_ = input.readInt32();
              break;
            }
            case 72: {
              bitField0_ |= 0x00000100;
              targetted_ = input.readBool();
              break;
            }
            case 85: {
              bitField0_ |= 0x00000200;
              size_ = input.readFloat();
              break;
            }
            case 93: {
              bitField0_ |= 0x00000400;
              castTime_ = input.readFloat();
              break;
            }
            case 101: {
              bitField0_ |= 0x00000800;
              coolDown_ = input.readFloat();
              break;
            }
            case 109: {
              bitField0_ |= 0x00001000;
              range_ = input.readFloat();
              break;
            }
            case 112: {
              bitField0_ |= 0x00002000;
              levelReq_ = input.readInt32();
              break;
            }
            case 120: {
              bitField0_ |= 0x00004000;
              spellLvl_ = input.readInt32();
              break;
            }
            case 128: {
              bitField0_ |= 0x00008000;
              researchCost_ = input.readInt32();
              break;
            }
            case 136: {
              bitField0_ |= 0x00010000;
              researchTime_ = input.readInt32();
              break;
            }
            case 144: {
              int rawValue = input.readEnum();
              com.lvl6.aoc2.proto.ResourceEnum.ResourceType value = com.lvl6.aoc2.proto.ResourceEnum.ResourceType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(18, rawValue);
              } else {
                bitField0_ |= 0x00020000;
                researchResource_ = value;
              }
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional int32 spellID = 1;
      private int spellID_ ;
      public boolean hasSpellID() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getSpellID() {
        return spellID_;
      }
      public Builder setSpellID(int value) {
        bitField0_ |= 0x00000001;
        spellID_ = value;
        onChanged();
        return this;
      }
      public Builder clearSpellID() {
        bitField0_ = (bitField0_ & ~0x00000001);
        spellID_ = 0;
        onChanged();
        return this;
      }
      
      // required .com.lvl6.aoc2.proto.ClassType classType = 2;
      private com.lvl6.aoc2.proto.ClassEnum.ClassType classType_ = com.lvl6.aoc2.proto.ClassEnum.ClassType.WARRIOR;
      public boolean hasClassType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public com.lvl6.aoc2.proto.ClassEnum.ClassType getClassType() {
        return classType_;
      }
      public Builder setClassType(com.lvl6.aoc2.proto.ClassEnum.ClassType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        classType_ = value;
        onChanged();
        return this;
      }
      public Builder clearClassType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        classType_ = com.lvl6.aoc2.proto.ClassEnum.ClassType.WARRIOR;
        onChanged();
        return this;
      }
      
      // optional string name = 3;
      private java.lang.Object name_ = "";
      public boolean hasName() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        name_ = value;
        onChanged();
        return this;
      }
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000004);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      void setName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        name_ = value;
        onChanged();
      }
      
      // optional .com.lvl6.aoc2.proto.SpellProto.FunctionType function = 4;
      private com.lvl6.aoc2.proto.Spell.SpellProto.FunctionType function_ = com.lvl6.aoc2.proto.Spell.SpellProto.FunctionType.ATTACK;
      public boolean hasFunction() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public com.lvl6.aoc2.proto.Spell.SpellProto.FunctionType getFunction() {
        return function_;
      }
      public Builder setFunction(com.lvl6.aoc2.proto.Spell.SpellProto.FunctionType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000008;
        function_ = value;
        onChanged();
        return this;
      }
      public Builder clearFunction() {
        bitField0_ = (bitField0_ & ~0x00000008);
        function_ = com.lvl6.aoc2.proto.Spell.SpellProto.FunctionType.ATTACK;
        onChanged();
        return this;
      }
      
      // optional int32 strength = 5;
      private int strength_ ;
      public boolean hasStrength() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public int getStrength() {
        return strength_;
      }
      public Builder setStrength(int value) {
        bitField0_ |= 0x00000010;
        strength_ = value;
        onChanged();
        return this;
      }
      public Builder clearStrength() {
        bitField0_ = (bitField0_ & ~0x00000010);
        strength_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 manaCost = 6;
      private int manaCost_ ;
      public boolean hasManaCost() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public int getManaCost() {
        return manaCost_;
      }
      public Builder setManaCost(int value) {
        bitField0_ |= 0x00000020;
        manaCost_ = value;
        onChanged();
        return this;
      }
      public Builder clearManaCost() {
        bitField0_ = (bitField0_ & ~0x00000020);
        manaCost_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 duration = 7;
      private int duration_ ;
      public boolean hasDuration() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public int getDuration() {
        return duration_;
      }
      public Builder setDuration(int value) {
        bitField0_ |= 0x00000040;
        duration_ = value;
        onChanged();
        return this;
      }
      public Builder clearDuration() {
        bitField0_ = (bitField0_ & ~0x00000040);
        duration_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 speed = 8;
      private int speed_ ;
      public boolean hasSpeed() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      public int getSpeed() {
        return speed_;
      }
      public Builder setSpeed(int value) {
        bitField0_ |= 0x00000080;
        speed_ = value;
        onChanged();
        return this;
      }
      public Builder clearSpeed() {
        bitField0_ = (bitField0_ & ~0x00000080);
        speed_ = 0;
        onChanged();
        return this;
      }
      
      // optional bool targetted = 9;
      private boolean targetted_ ;
      public boolean hasTargetted() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      public boolean getTargetted() {
        return targetted_;
      }
      public Builder setTargetted(boolean value) {
        bitField0_ |= 0x00000100;
        targetted_ = value;
        onChanged();
        return this;
      }
      public Builder clearTargetted() {
        bitField0_ = (bitField0_ & ~0x00000100);
        targetted_ = false;
        onChanged();
        return this;
      }
      
      // optional float size = 10;
      private float size_ ;
      public boolean hasSize() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      public float getSize() {
        return size_;
      }
      public Builder setSize(float value) {
        bitField0_ |= 0x00000200;
        size_ = value;
        onChanged();
        return this;
      }
      public Builder clearSize() {
        bitField0_ = (bitField0_ & ~0x00000200);
        size_ = 0F;
        onChanged();
        return this;
      }
      
      // optional float castTime = 11;
      private float castTime_ ;
      public boolean hasCastTime() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      public float getCastTime() {
        return castTime_;
      }
      public Builder setCastTime(float value) {
        bitField0_ |= 0x00000400;
        castTime_ = value;
        onChanged();
        return this;
      }
      public Builder clearCastTime() {
        bitField0_ = (bitField0_ & ~0x00000400);
        castTime_ = 0F;
        onChanged();
        return this;
      }
      
      // optional float coolDown = 12;
      private float coolDown_ ;
      public boolean hasCoolDown() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      public float getCoolDown() {
        return coolDown_;
      }
      public Builder setCoolDown(float value) {
        bitField0_ |= 0x00000800;
        coolDown_ = value;
        onChanged();
        return this;
      }
      public Builder clearCoolDown() {
        bitField0_ = (bitField0_ & ~0x00000800);
        coolDown_ = 0F;
        onChanged();
        return this;
      }
      
      // optional float range = 13;
      private float range_ ;
      public boolean hasRange() {
        return ((bitField0_ & 0x00001000) == 0x00001000);
      }
      public float getRange() {
        return range_;
      }
      public Builder setRange(float value) {
        bitField0_ |= 0x00001000;
        range_ = value;
        onChanged();
        return this;
      }
      public Builder clearRange() {
        bitField0_ = (bitField0_ & ~0x00001000);
        range_ = 0F;
        onChanged();
        return this;
      }
      
      // optional int32 levelReq = 14;
      private int levelReq_ ;
      public boolean hasLevelReq() {
        return ((bitField0_ & 0x00002000) == 0x00002000);
      }
      public int getLevelReq() {
        return levelReq_;
      }
      public Builder setLevelReq(int value) {
        bitField0_ |= 0x00002000;
        levelReq_ = value;
        onChanged();
        return this;
      }
      public Builder clearLevelReq() {
        bitField0_ = (bitField0_ & ~0x00002000);
        levelReq_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 spellLvl = 15;
      private int spellLvl_ ;
      public boolean hasSpellLvl() {
        return ((bitField0_ & 0x00004000) == 0x00004000);
      }
      public int getSpellLvl() {
        return spellLvl_;
      }
      public Builder setSpellLvl(int value) {
        bitField0_ |= 0x00004000;
        spellLvl_ = value;
        onChanged();
        return this;
      }
      public Builder clearSpellLvl() {
        bitField0_ = (bitField0_ & ~0x00004000);
        spellLvl_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 researchCost = 16;
      private int researchCost_ ;
      public boolean hasResearchCost() {
        return ((bitField0_ & 0x00008000) == 0x00008000);
      }
      public int getResearchCost() {
        return researchCost_;
      }
      public Builder setResearchCost(int value) {
        bitField0_ |= 0x00008000;
        researchCost_ = value;
        onChanged();
        return this;
      }
      public Builder clearResearchCost() {
        bitField0_ = (bitField0_ & ~0x00008000);
        researchCost_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 researchTime = 17;
      private int researchTime_ ;
      public boolean hasResearchTime() {
        return ((bitField0_ & 0x00010000) == 0x00010000);
      }
      public int getResearchTime() {
        return researchTime_;
      }
      public Builder setResearchTime(int value) {
        bitField0_ |= 0x00010000;
        researchTime_ = value;
        onChanged();
        return this;
      }
      public Builder clearResearchTime() {
        bitField0_ = (bitField0_ & ~0x00010000);
        researchTime_ = 0;
        onChanged();
        return this;
      }
      
      // required .com.lvl6.aoc2.proto.ResourceType researchResource = 18;
      private com.lvl6.aoc2.proto.ResourceEnum.ResourceType researchResource_ = com.lvl6.aoc2.proto.ResourceEnum.ResourceType.GOLD;
      public boolean hasResearchResource() {
        return ((bitField0_ & 0x00020000) == 0x00020000);
      }
      public com.lvl6.aoc2.proto.ResourceEnum.ResourceType getResearchResource() {
        return researchResource_;
      }
      public Builder setResearchResource(com.lvl6.aoc2.proto.ResourceEnum.ResourceType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00020000;
        researchResource_ = value;
        onChanged();
        return this;
      }
      public Builder clearResearchResource() {
        bitField0_ = (bitField0_ & ~0x00020000);
        researchResource_ = com.lvl6.aoc2.proto.ResourceEnum.ResourceType.GOLD;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.lvl6.aoc2.proto.SpellProto)
    }
    
    static {
      defaultInstance = new SpellProto(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.lvl6.aoc2.proto.SpellProto)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lvl6_aoc2_proto_SpellProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_lvl6_aoc2_proto_SpellProto_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020SpellProto.proto\022\023com.lvl6.aoc2.proto\032" +
      "\017ClassType.proto\032\022ResourceType.proto\"\236\004\n" +
      "\nSpellProto\022\017\n\007spellID\030\001 \001(\005\0221\n\tclassTyp" +
      "e\030\002 \002(\0162\036.com.lvl6.aoc2.proto.ClassType\022" +
      "\014\n\004name\030\003 \001(\t\022>\n\010function\030\004 \001(\0162,.com.lv" +
      "l6.aoc2.proto.SpellProto.FunctionType\022\020\n" +
      "\010strength\030\005 \001(\005\022\020\n\010manaCost\030\006 \001(\005\022\020\n\010dur" +
      "ation\030\007 \001(\005\022\r\n\005speed\030\010 \001(\005\022\021\n\ttargetted\030" +
      "\t \001(\010\022\014\n\004size\030\n \001(\002\022\020\n\010castTime\030\013 \001(\002\022\020\n" +
      "\010coolDown\030\014 \001(\002\022\r\n\005range\030\r \001(\002\022\020\n\010levelR",
      "eq\030\016 \001(\005\022\020\n\010spellLvl\030\017 \001(\005\022\024\n\014researchCo" +
      "st\030\020 \001(\005\022\024\n\014researchTime\030\021 \001(\005\022;\n\020resear" +
      "chResource\030\022 \002(\0162!.com.lvl6.aoc2.proto.R" +
      "esourceType\"X\n\014FunctionType\022\n\n\006ATTACK\020\000\022" +
      "\r\n\tFLAT_BUFF\020\001\022\016\n\nSCALE_BUFF\020\002\022\r\n\tHEAL_S" +
      "ELF\020\003\022\016\n\nHEAL_OTHER\020\004B\007B\005Spell"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_lvl6_aoc2_proto_SpellProto_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_lvl6_aoc2_proto_SpellProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_lvl6_aoc2_proto_SpellProto_descriptor,
              new java.lang.String[] { "SpellID", "ClassType", "Name", "Function", "Strength", "ManaCost", "Duration", "Speed", "Targetted", "Size", "CastTime", "CoolDown", "Range", "LevelReq", "SpellLvl", "ResearchCost", "ResearchTime", "ResearchResource", },
              com.lvl6.aoc2.proto.Spell.SpellProto.class,
              com.lvl6.aoc2.proto.Spell.SpellProto.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.lvl6.aoc2.proto.ClassEnum.getDescriptor(),
          com.lvl6.aoc2.proto.ResourceEnum.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
