// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StructProto.proto

package com.lvl6.aoc2.proto;

public final class Structure {
  private Structure() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface StructureProtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 structureID = 1;
    /**
     * <code>optional int32 structureID = 1;</code>
     */
    boolean hasStructureID();
    /**
     * <code>optional int32 structureID = 1;</code>
     */
    int getStructureID();

    // optional .com.lvl6.aoc2.proto.StructureProto.StructureFunction function = 2;
    /**
     * <code>optional .com.lvl6.aoc2.proto.StructureProto.StructureFunction function = 2;</code>
     */
    boolean hasFunction();
    /**
     * <code>optional .com.lvl6.aoc2.proto.StructureProto.StructureFunction function = 2;</code>
     */
    com.lvl6.aoc2.proto.Structure.StructureProto.StructureFunction getFunction();

    // optional int32 buildCost = 3;
    /**
     * <code>optional int32 buildCost = 3;</code>
     */
    boolean hasBuildCost();
    /**
     * <code>optional int32 buildCost = 3;</code>
     */
    int getBuildCost();

    // optional int32 buildTime = 4;
    /**
     * <code>optional int32 buildTime = 4;</code>
     */
    boolean hasBuildTime();
    /**
     * <code>optional int32 buildTime = 4;</code>
     */
    int getBuildTime();

    // required .com.lvl6.aoc2.proto.ResourceType buildResource = 5;
    /**
     * <code>required .com.lvl6.aoc2.proto.ResourceType buildResource = 5;</code>
     */
    boolean hasBuildResource();
    /**
     * <code>required .com.lvl6.aoc2.proto.ResourceType buildResource = 5;</code>
     */
    com.lvl6.aoc2.proto.ResourceEnum.ResourceType getBuildResource();

    // optional int32 upgradeTownHallLevel = 6;
    /**
     * <code>optional int32 upgradeTownHallLevel = 6;</code>
     */
    boolean hasUpgradeTownHallLevel();
    /**
     * <code>optional int32 upgradeTownHallLevel = 6;</code>
     */
    int getUpgradeTownHallLevel();

    // optional .com.lvl6.aoc2.proto.CoordinateProto size = 7;
    /**
     * <code>optional .com.lvl6.aoc2.proto.CoordinateProto size = 7;</code>
     */
    boolean hasSize();
    /**
     * <code>optional .com.lvl6.aoc2.proto.CoordinateProto size = 7;</code>
     */
    com.lvl6.aoc2.proto.Coordiante.CoordinateProto getSize();
    /**
     * <code>optional .com.lvl6.aoc2.proto.CoordinateProto size = 7;</code>
     */
    com.lvl6.aoc2.proto.Coordiante.CoordinateProtoOrBuilder getSizeOrBuilder();

    // optional int32 buildSpeedUpBaseCost = 8;
    /**
     * <code>optional int32 buildSpeedUpBaseCost = 8;</code>
     */
    boolean hasBuildSpeedUpBaseCost();
    /**
     * <code>optional int32 buildSpeedUpBaseCost = 8;</code>
     */
    int getBuildSpeedUpBaseCost();

    // optional int32 functionValue = 9;
    /**
     * <code>optional int32 functionValue = 9;</code>
     */
    boolean hasFunctionValue();
    /**
     * <code>optional int32 functionValue = 9;</code>
     */
    int getFunctionValue();

    // required .com.lvl6.aoc2.proto.ResourceType functionResource = 10;
    /**
     * <code>required .com.lvl6.aoc2.proto.ResourceType functionResource = 10;</code>
     */
    boolean hasFunctionResource();
    /**
     * <code>required .com.lvl6.aoc2.proto.ResourceType functionResource = 10;</code>
     */
    com.lvl6.aoc2.proto.ResourceEnum.ResourceType getFunctionResource();

    // optional int32 speedUpFunctionBaseCost = 11;
    /**
     * <code>optional int32 speedUpFunctionBaseCost = 11;</code>
     */
    boolean hasSpeedUpFunctionBaseCost();
    /**
     * <code>optional int32 speedUpFunctionBaseCost = 11;</code>
     */
    int getSpeedUpFunctionBaseCost();

    // optional int32 capacity = 12;
    /**
     * <code>optional int32 capacity = 12;</code>
     */
    boolean hasCapacity();
    /**
     * <code>optional int32 capacity = 12;</code>
     */
    int getCapacity();

    // optional int32 level = 13;
    /**
     * <code>optional int32 level = 13;</code>
     */
    boolean hasLevel();
    /**
     * <code>optional int32 level = 13;</code>
     */
    int getLevel();

    // optional string name = 14;
    /**
     * <code>optional string name = 14;</code>
     */
    boolean hasName();
    /**
     * <code>optional string name = 14;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 14;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    // optional string imageName = 15;
    /**
     * <code>optional string imageName = 15;</code>
     */
    boolean hasImageName();
    /**
     * <code>optional string imageName = 15;</code>
     */
    java.lang.String getImageName();
    /**
     * <code>optional string imageName = 15;</code>
     */
    com.google.protobuf.ByteString
        getImageNameBytes();
  }
  /**
   * Protobuf type {@code com.lvl6.aoc2.proto.StructureProto}
   */
  public static final class StructureProto extends
      com.google.protobuf.GeneratedMessage
      implements StructureProtoOrBuilder {
    // Use StructureProto.newBuilder() to construct.
    private StructureProto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private StructureProto(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final StructureProto defaultInstance;
    public static StructureProto getDefaultInstance() {
      return defaultInstance;
    }

    public StructureProto getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private StructureProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              structureID_ = input.readInt32();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              com.lvl6.aoc2.proto.Structure.StructureProto.StructureFunction value = com.lvl6.aoc2.proto.Structure.StructureProto.StructureFunction.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                function_ = value;
              }
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              buildCost_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              buildTime_ = input.readInt32();
              break;
            }
            case 40: {
              int rawValue = input.readEnum();
              com.lvl6.aoc2.proto.ResourceEnum.ResourceType value = com.lvl6.aoc2.proto.ResourceEnum.ResourceType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(5, rawValue);
              } else {
                bitField0_ |= 0x00000010;
                buildResource_ = value;
              }
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              upgradeTownHallLevel_ = input.readInt32();
              break;
            }
            case 58: {
              com.lvl6.aoc2.proto.Coordiante.CoordinateProto.Builder subBuilder = null;
              if (((bitField0_ & 0x00000040) == 0x00000040)) {
                subBuilder = size_.toBuilder();
              }
              size_ = input.readMessage(com.lvl6.aoc2.proto.Coordiante.CoordinateProto.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(size_);
                size_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000040;
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              buildSpeedUpBaseCost_ = input.readInt32();
              break;
            }
            case 72: {
              bitField0_ |= 0x00000100;
              functionValue_ = input.readInt32();
              break;
            }
            case 80: {
              int rawValue = input.readEnum();
              com.lvl6.aoc2.proto.ResourceEnum.ResourceType value = com.lvl6.aoc2.proto.ResourceEnum.ResourceType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(10, rawValue);
              } else {
                bitField0_ |= 0x00000200;
                functionResource_ = value;
              }
              break;
            }
            case 88: {
              bitField0_ |= 0x00000400;
              speedUpFunctionBaseCost_ = input.readInt32();
              break;
            }
            case 96: {
              bitField0_ |= 0x00000800;
              capacity_ = input.readInt32();
              break;
            }
            case 104: {
              bitField0_ |= 0x00001000;
              level_ = input.readInt32();
              break;
            }
            case 114: {
              bitField0_ |= 0x00002000;
              name_ = input.readBytes();
              break;
            }
            case 122: {
              bitField0_ |= 0x00004000;
              imageName_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lvl6.aoc2.proto.Structure.internal_static_com_lvl6_aoc2_proto_StructureProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lvl6.aoc2.proto.Structure.internal_static_com_lvl6_aoc2_proto_StructureProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.lvl6.aoc2.proto.Structure.StructureProto.class, com.lvl6.aoc2.proto.Structure.StructureProto.Builder.class);
    }

    public static com.google.protobuf.Parser<StructureProto> PARSER =
        new com.google.protobuf.AbstractParser<StructureProto>() {
      public StructureProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new StructureProto(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<StructureProto> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code com.lvl6.aoc2.proto.StructureProto.StructureFunction}
     */
    public enum StructureFunction
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>TOWN_HALL = 0;</code>
       */
      TOWN_HALL(0, 0),
      /**
       * <code>INCOME = 1;</code>
       */
      INCOME(1, 1),
      /**
       * <code>STORAGE = 2;</code>
       */
      STORAGE(2, 2),
      /**
       * <code>BLACKSMITH = 3;</code>
       */
      BLACKSMITH(3, 3),
      /**
       * <code>LIBRARY = 4;</code>
       */
      LIBRARY(4, 4),
      /**
       * <code>FUSION = 5;</code>
       */
      FUSION(5, 5),
      /**
       * <code>DECORATION = 6;</code>
       */
      DECORATION(6, 6),
      ;

      /**
       * <code>TOWN_HALL = 0;</code>
       */
      public static final int TOWN_HALL_VALUE = 0;
      /**
       * <code>INCOME = 1;</code>
       */
      public static final int INCOME_VALUE = 1;
      /**
       * <code>STORAGE = 2;</code>
       */
      public static final int STORAGE_VALUE = 2;
      /**
       * <code>BLACKSMITH = 3;</code>
       */
      public static final int BLACKSMITH_VALUE = 3;
      /**
       * <code>LIBRARY = 4;</code>
       */
      public static final int LIBRARY_VALUE = 4;
      /**
       * <code>FUSION = 5;</code>
       */
      public static final int FUSION_VALUE = 5;
      /**
       * <code>DECORATION = 6;</code>
       */
      public static final int DECORATION_VALUE = 6;


      public final int getNumber() { return value; }

      public static StructureFunction valueOf(int value) {
        switch (value) {
          case 0: return TOWN_HALL;
          case 1: return INCOME;
          case 2: return STORAGE;
          case 3: return BLACKSMITH;
          case 4: return LIBRARY;
          case 5: return FUSION;
          case 6: return DECORATION;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<StructureFunction>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<StructureFunction>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<StructureFunction>() {
              public StructureFunction findValueByNumber(int number) {
                return StructureFunction.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.lvl6.aoc2.proto.Structure.StructureProto.getDescriptor().getEnumTypes().get(0);
      }

      private static final StructureFunction[] VALUES = values();

      public static StructureFunction valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private StructureFunction(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.lvl6.aoc2.proto.StructureProto.StructureFunction)
    }

    private int bitField0_;
    // optional int32 structureID = 1;
    public static final int STRUCTUREID_FIELD_NUMBER = 1;
    private int structureID_;
    /**
     * <code>optional int32 structureID = 1;</code>
     */
    public boolean hasStructureID() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 structureID = 1;</code>
     */
    public int getStructureID() {
      return structureID_;
    }

    // optional .com.lvl6.aoc2.proto.StructureProto.StructureFunction function = 2;
    public static final int FUNCTION_FIELD_NUMBER = 2;
    private com.lvl6.aoc2.proto.Structure.StructureProto.StructureFunction function_;
    /**
     * <code>optional .com.lvl6.aoc2.proto.StructureProto.StructureFunction function = 2;</code>
     */
    public boolean hasFunction() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .com.lvl6.aoc2.proto.StructureProto.StructureFunction function = 2;</code>
     */
    public com.lvl6.aoc2.proto.Structure.StructureProto.StructureFunction getFunction() {
      return function_;
    }

    // optional int32 buildCost = 3;
    public static final int BUILDCOST_FIELD_NUMBER = 3;
    private int buildCost_;
    /**
     * <code>optional int32 buildCost = 3;</code>
     */
    public boolean hasBuildCost() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 buildCost = 3;</code>
     */
    public int getBuildCost() {
      return buildCost_;
    }

    // optional int32 buildTime = 4;
    public static final int BUILDTIME_FIELD_NUMBER = 4;
    private int buildTime_;
    /**
     * <code>optional int32 buildTime = 4;</code>
     */
    public boolean hasBuildTime() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 buildTime = 4;</code>
     */
    public int getBuildTime() {
      return buildTime_;
    }

    // required .com.lvl6.aoc2.proto.ResourceType buildResource = 5;
    public static final int BUILDRESOURCE_FIELD_NUMBER = 5;
    private com.lvl6.aoc2.proto.ResourceEnum.ResourceType buildResource_;
    /**
     * <code>required .com.lvl6.aoc2.proto.ResourceType buildResource = 5;</code>
     */
    public boolean hasBuildResource() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required .com.lvl6.aoc2.proto.ResourceType buildResource = 5;</code>
     */
    public com.lvl6.aoc2.proto.ResourceEnum.ResourceType getBuildResource() {
      return buildResource_;
    }

    // optional int32 upgradeTownHallLevel = 6;
    public static final int UPGRADETOWNHALLLEVEL_FIELD_NUMBER = 6;
    private int upgradeTownHallLevel_;
    /**
     * <code>optional int32 upgradeTownHallLevel = 6;</code>
     */
    public boolean hasUpgradeTownHallLevel() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional int32 upgradeTownHallLevel = 6;</code>
     */
    public int getUpgradeTownHallLevel() {
      return upgradeTownHallLevel_;
    }

    // optional .com.lvl6.aoc2.proto.CoordinateProto size = 7;
    public static final int SIZE_FIELD_NUMBER = 7;
    private com.lvl6.aoc2.proto.Coordiante.CoordinateProto size_;
    /**
     * <code>optional .com.lvl6.aoc2.proto.CoordinateProto size = 7;</code>
     */
    public boolean hasSize() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional .com.lvl6.aoc2.proto.CoordinateProto size = 7;</code>
     */
    public com.lvl6.aoc2.proto.Coordiante.CoordinateProto getSize() {
      return size_;
    }
    /**
     * <code>optional .com.lvl6.aoc2.proto.CoordinateProto size = 7;</code>
     */
    public com.lvl6.aoc2.proto.Coordiante.CoordinateProtoOrBuilder getSizeOrBuilder() {
      return size_;
    }

    // optional int32 buildSpeedUpBaseCost = 8;
    public static final int BUILDSPEEDUPBASECOST_FIELD_NUMBER = 8;
    private int buildSpeedUpBaseCost_;
    /**
     * <code>optional int32 buildSpeedUpBaseCost = 8;</code>
     */
    public boolean hasBuildSpeedUpBaseCost() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional int32 buildSpeedUpBaseCost = 8;</code>
     */
    public int getBuildSpeedUpBaseCost() {
      return buildSpeedUpBaseCost_;
    }

    // optional int32 functionValue = 9;
    public static final int FUNCTIONVALUE_FIELD_NUMBER = 9;
    private int functionValue_;
    /**
     * <code>optional int32 functionValue = 9;</code>
     */
    public boolean hasFunctionValue() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional int32 functionValue = 9;</code>
     */
    public int getFunctionValue() {
      return functionValue_;
    }

    // required .com.lvl6.aoc2.proto.ResourceType functionResource = 10;
    public static final int FUNCTIONRESOURCE_FIELD_NUMBER = 10;
    private com.lvl6.aoc2.proto.ResourceEnum.ResourceType functionResource_;
    /**
     * <code>required .com.lvl6.aoc2.proto.ResourceType functionResource = 10;</code>
     */
    public boolean hasFunctionResource() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>required .com.lvl6.aoc2.proto.ResourceType functionResource = 10;</code>
     */
    public com.lvl6.aoc2.proto.ResourceEnum.ResourceType getFunctionResource() {
      return functionResource_;
    }

    // optional int32 speedUpFunctionBaseCost = 11;
    public static final int SPEEDUPFUNCTIONBASECOST_FIELD_NUMBER = 11;
    private int speedUpFunctionBaseCost_;
    /**
     * <code>optional int32 speedUpFunctionBaseCost = 11;</code>
     */
    public boolean hasSpeedUpFunctionBaseCost() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <code>optional int32 speedUpFunctionBaseCost = 11;</code>
     */
    public int getSpeedUpFunctionBaseCost() {
      return speedUpFunctionBaseCost_;
    }

    // optional int32 capacity = 12;
    public static final int CAPACITY_FIELD_NUMBER = 12;
    private int capacity_;
    /**
     * <code>optional int32 capacity = 12;</code>
     */
    public boolean hasCapacity() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    /**
     * <code>optional int32 capacity = 12;</code>
     */
    public int getCapacity() {
      return capacity_;
    }

    // optional int32 level = 13;
    public static final int LEVEL_FIELD_NUMBER = 13;
    private int level_;
    /**
     * <code>optional int32 level = 13;</code>
     */
    public boolean hasLevel() {
      return ((bitField0_ & 0x00001000) == 0x00001000);
    }
    /**
     * <code>optional int32 level = 13;</code>
     */
    public int getLevel() {
      return level_;
    }

    // optional string name = 14;
    public static final int NAME_FIELD_NUMBER = 14;
    private java.lang.Object name_;
    /**
     * <code>optional string name = 14;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00002000) == 0x00002000);
    }
    /**
     * <code>optional string name = 14;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string name = 14;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string imageName = 15;
    public static final int IMAGENAME_FIELD_NUMBER = 15;
    private java.lang.Object imageName_;
    /**
     * <code>optional string imageName = 15;</code>
     */
    public boolean hasImageName() {
      return ((bitField0_ & 0x00004000) == 0x00004000);
    }
    /**
     * <code>optional string imageName = 15;</code>
     */
    public java.lang.String getImageName() {
      java.lang.Object ref = imageName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          imageName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string imageName = 15;</code>
     */
    public com.google.protobuf.ByteString
        getImageNameBytes() {
      java.lang.Object ref = imageName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        imageName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      structureID_ = 0;
      function_ = com.lvl6.aoc2.proto.Structure.StructureProto.StructureFunction.TOWN_HALL;
      buildCost_ = 0;
      buildTime_ = 0;
      buildResource_ = com.lvl6.aoc2.proto.ResourceEnum.ResourceType.GOLD;
      upgradeTownHallLevel_ = 0;
      size_ = com.lvl6.aoc2.proto.Coordiante.CoordinateProto.getDefaultInstance();
      buildSpeedUpBaseCost_ = 0;
      functionValue_ = 0;
      functionResource_ = com.lvl6.aoc2.proto.ResourceEnum.ResourceType.GOLD;
      speedUpFunctionBaseCost_ = 0;
      capacity_ = 0;
      level_ = 0;
      name_ = "";
      imageName_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasBuildResource()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFunctionResource()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, structureID_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, function_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, buildCost_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, buildTime_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeEnum(5, buildResource_.getNumber());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(6, upgradeTownHallLevel_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeMessage(7, size_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeInt32(8, buildSpeedUpBaseCost_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeInt32(9, functionValue_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeEnum(10, functionResource_.getNumber());
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeInt32(11, speedUpFunctionBaseCost_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeInt32(12, capacity_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        output.writeInt32(13, level_);
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        output.writeBytes(14, getNameBytes());
      }
      if (((bitField0_ & 0x00004000) == 0x00004000)) {
        output.writeBytes(15, getImageNameBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, structureID_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, function_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, buildCost_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, buildTime_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, buildResource_.getNumber());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, upgradeTownHallLevel_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, size_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, buildSpeedUpBaseCost_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, functionValue_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(10, functionResource_.getNumber());
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(11, speedUpFunctionBaseCost_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(12, capacity_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(13, level_);
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(14, getNameBytes());
      }
      if (((bitField0_ & 0x00004000) == 0x00004000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(15, getImageNameBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.lvl6.aoc2.proto.Structure.StructureProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lvl6.aoc2.proto.Structure.StructureProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lvl6.aoc2.proto.Structure.StructureProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lvl6.aoc2.proto.Structure.StructureProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lvl6.aoc2.proto.Structure.StructureProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.lvl6.aoc2.proto.Structure.StructureProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.lvl6.aoc2.proto.Structure.StructureProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.lvl6.aoc2.proto.Structure.StructureProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.lvl6.aoc2.proto.Structure.StructureProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.lvl6.aoc2.proto.Structure.StructureProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.lvl6.aoc2.proto.Structure.StructureProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.lvl6.aoc2.proto.StructureProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.lvl6.aoc2.proto.Structure.StructureProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.lvl6.aoc2.proto.Structure.internal_static_com_lvl6_aoc2_proto_StructureProto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.lvl6.aoc2.proto.Structure.internal_static_com_lvl6_aoc2_proto_StructureProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.lvl6.aoc2.proto.Structure.StructureProto.class, com.lvl6.aoc2.proto.Structure.StructureProto.Builder.class);
      }

      // Construct using com.lvl6.aoc2.proto.Structure.StructureProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getSizeFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        structureID_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        function_ = com.lvl6.aoc2.proto.Structure.StructureProto.StructureFunction.TOWN_HALL;
        bitField0_ = (bitField0_ & ~0x00000002);
        buildCost_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        buildTime_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        buildResource_ = com.lvl6.aoc2.proto.ResourceEnum.ResourceType.GOLD;
        bitField0_ = (bitField0_ & ~0x00000010);
        upgradeTownHallLevel_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        if (sizeBuilder_ == null) {
          size_ = com.lvl6.aoc2.proto.Coordiante.CoordinateProto.getDefaultInstance();
        } else {
          sizeBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000040);
        buildSpeedUpBaseCost_ = 0;
        bitField0_ = (bitField0_ & ~0x00000080);
        functionValue_ = 0;
        bitField0_ = (bitField0_ & ~0x00000100);
        functionResource_ = com.lvl6.aoc2.proto.ResourceEnum.ResourceType.GOLD;
        bitField0_ = (bitField0_ & ~0x00000200);
        speedUpFunctionBaseCost_ = 0;
        bitField0_ = (bitField0_ & ~0x00000400);
        capacity_ = 0;
        bitField0_ = (bitField0_ & ~0x00000800);
        level_ = 0;
        bitField0_ = (bitField0_ & ~0x00001000);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00002000);
        imageName_ = "";
        bitField0_ = (bitField0_ & ~0x00004000);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.lvl6.aoc2.proto.Structure.internal_static_com_lvl6_aoc2_proto_StructureProto_descriptor;
      }

      public com.lvl6.aoc2.proto.Structure.StructureProto getDefaultInstanceForType() {
        return com.lvl6.aoc2.proto.Structure.StructureProto.getDefaultInstance();
      }

      public com.lvl6.aoc2.proto.Structure.StructureProto build() {
        com.lvl6.aoc2.proto.Structure.StructureProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.lvl6.aoc2.proto.Structure.StructureProto buildPartial() {
        com.lvl6.aoc2.proto.Structure.StructureProto result = new com.lvl6.aoc2.proto.Structure.StructureProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.structureID_ = structureID_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.function_ = function_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.buildCost_ = buildCost_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.buildTime_ = buildTime_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.buildResource_ = buildResource_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.upgradeTownHallLevel_ = upgradeTownHallLevel_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        if (sizeBuilder_ == null) {
          result.size_ = size_;
        } else {
          result.size_ = sizeBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.buildSpeedUpBaseCost_ = buildSpeedUpBaseCost_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.functionValue_ = functionValue_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.functionResource_ = functionResource_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.speedUpFunctionBaseCost_ = speedUpFunctionBaseCost_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000800;
        }
        result.capacity_ = capacity_;
        if (((from_bitField0_ & 0x00001000) == 0x00001000)) {
          to_bitField0_ |= 0x00001000;
        }
        result.level_ = level_;
        if (((from_bitField0_ & 0x00002000) == 0x00002000)) {
          to_bitField0_ |= 0x00002000;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00004000) == 0x00004000)) {
          to_bitField0_ |= 0x00004000;
        }
        result.imageName_ = imageName_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.lvl6.aoc2.proto.Structure.StructureProto) {
          return mergeFrom((com.lvl6.aoc2.proto.Structure.StructureProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.lvl6.aoc2.proto.Structure.StructureProto other) {
        if (other == com.lvl6.aoc2.proto.Structure.StructureProto.getDefaultInstance()) return this;
        if (other.hasStructureID()) {
          setStructureID(other.getStructureID());
        }
        if (other.hasFunction()) {
          setFunction(other.getFunction());
        }
        if (other.hasBuildCost()) {
          setBuildCost(other.getBuildCost());
        }
        if (other.hasBuildTime()) {
          setBuildTime(other.getBuildTime());
        }
        if (other.hasBuildResource()) {
          setBuildResource(other.getBuildResource());
        }
        if (other.hasUpgradeTownHallLevel()) {
          setUpgradeTownHallLevel(other.getUpgradeTownHallLevel());
        }
        if (other.hasSize()) {
          mergeSize(other.getSize());
        }
        if (other.hasBuildSpeedUpBaseCost()) {
          setBuildSpeedUpBaseCost(other.getBuildSpeedUpBaseCost());
        }
        if (other.hasFunctionValue()) {
          setFunctionValue(other.getFunctionValue());
        }
        if (other.hasFunctionResource()) {
          setFunctionResource(other.getFunctionResource());
        }
        if (other.hasSpeedUpFunctionBaseCost()) {
          setSpeedUpFunctionBaseCost(other.getSpeedUpFunctionBaseCost());
        }
        if (other.hasCapacity()) {
          setCapacity(other.getCapacity());
        }
        if (other.hasLevel()) {
          setLevel(other.getLevel());
        }
        if (other.hasName()) {
          bitField0_ |= 0x00002000;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasImageName()) {
          bitField0_ |= 0x00004000;
          imageName_ = other.imageName_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasBuildResource()) {
          
          return false;
        }
        if (!hasFunctionResource()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.lvl6.aoc2.proto.Structure.StructureProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.lvl6.aoc2.proto.Structure.StructureProto) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 structureID = 1;
      private int structureID_ ;
      /**
       * <code>optional int32 structureID = 1;</code>
       */
      public boolean hasStructureID() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 structureID = 1;</code>
       */
      public int getStructureID() {
        return structureID_;
      }
      /**
       * <code>optional int32 structureID = 1;</code>
       */
      public Builder setStructureID(int value) {
        bitField0_ |= 0x00000001;
        structureID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 structureID = 1;</code>
       */
      public Builder clearStructureID() {
        bitField0_ = (bitField0_ & ~0x00000001);
        structureID_ = 0;
        onChanged();
        return this;
      }

      // optional .com.lvl6.aoc2.proto.StructureProto.StructureFunction function = 2;
      private com.lvl6.aoc2.proto.Structure.StructureProto.StructureFunction function_ = com.lvl6.aoc2.proto.Structure.StructureProto.StructureFunction.TOWN_HALL;
      /**
       * <code>optional .com.lvl6.aoc2.proto.StructureProto.StructureFunction function = 2;</code>
       */
      public boolean hasFunction() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .com.lvl6.aoc2.proto.StructureProto.StructureFunction function = 2;</code>
       */
      public com.lvl6.aoc2.proto.Structure.StructureProto.StructureFunction getFunction() {
        return function_;
      }
      /**
       * <code>optional .com.lvl6.aoc2.proto.StructureProto.StructureFunction function = 2;</code>
       */
      public Builder setFunction(com.lvl6.aoc2.proto.Structure.StructureProto.StructureFunction value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        function_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .com.lvl6.aoc2.proto.StructureProto.StructureFunction function = 2;</code>
       */
      public Builder clearFunction() {
        bitField0_ = (bitField0_ & ~0x00000002);
        function_ = com.lvl6.aoc2.proto.Structure.StructureProto.StructureFunction.TOWN_HALL;
        onChanged();
        return this;
      }

      // optional int32 buildCost = 3;
      private int buildCost_ ;
      /**
       * <code>optional int32 buildCost = 3;</code>
       */
      public boolean hasBuildCost() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 buildCost = 3;</code>
       */
      public int getBuildCost() {
        return buildCost_;
      }
      /**
       * <code>optional int32 buildCost = 3;</code>
       */
      public Builder setBuildCost(int value) {
        bitField0_ |= 0x00000004;
        buildCost_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 buildCost = 3;</code>
       */
      public Builder clearBuildCost() {
        bitField0_ = (bitField0_ & ~0x00000004);
        buildCost_ = 0;
        onChanged();
        return this;
      }

      // optional int32 buildTime = 4;
      private int buildTime_ ;
      /**
       * <code>optional int32 buildTime = 4;</code>
       */
      public boolean hasBuildTime() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 buildTime = 4;</code>
       */
      public int getBuildTime() {
        return buildTime_;
      }
      /**
       * <code>optional int32 buildTime = 4;</code>
       */
      public Builder setBuildTime(int value) {
        bitField0_ |= 0x00000008;
        buildTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 buildTime = 4;</code>
       */
      public Builder clearBuildTime() {
        bitField0_ = (bitField0_ & ~0x00000008);
        buildTime_ = 0;
        onChanged();
        return this;
      }

      // required .com.lvl6.aoc2.proto.ResourceType buildResource = 5;
      private com.lvl6.aoc2.proto.ResourceEnum.ResourceType buildResource_ = com.lvl6.aoc2.proto.ResourceEnum.ResourceType.GOLD;
      /**
       * <code>required .com.lvl6.aoc2.proto.ResourceType buildResource = 5;</code>
       */
      public boolean hasBuildResource() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required .com.lvl6.aoc2.proto.ResourceType buildResource = 5;</code>
       */
      public com.lvl6.aoc2.proto.ResourceEnum.ResourceType getBuildResource() {
        return buildResource_;
      }
      /**
       * <code>required .com.lvl6.aoc2.proto.ResourceType buildResource = 5;</code>
       */
      public Builder setBuildResource(com.lvl6.aoc2.proto.ResourceEnum.ResourceType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000010;
        buildResource_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .com.lvl6.aoc2.proto.ResourceType buildResource = 5;</code>
       */
      public Builder clearBuildResource() {
        bitField0_ = (bitField0_ & ~0x00000010);
        buildResource_ = com.lvl6.aoc2.proto.ResourceEnum.ResourceType.GOLD;
        onChanged();
        return this;
      }

      // optional int32 upgradeTownHallLevel = 6;
      private int upgradeTownHallLevel_ ;
      /**
       * <code>optional int32 upgradeTownHallLevel = 6;</code>
       */
      public boolean hasUpgradeTownHallLevel() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional int32 upgradeTownHallLevel = 6;</code>
       */
      public int getUpgradeTownHallLevel() {
        return upgradeTownHallLevel_;
      }
      /**
       * <code>optional int32 upgradeTownHallLevel = 6;</code>
       */
      public Builder setUpgradeTownHallLevel(int value) {
        bitField0_ |= 0x00000020;
        upgradeTownHallLevel_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 upgradeTownHallLevel = 6;</code>
       */
      public Builder clearUpgradeTownHallLevel() {
        bitField0_ = (bitField0_ & ~0x00000020);
        upgradeTownHallLevel_ = 0;
        onChanged();
        return this;
      }

      // optional .com.lvl6.aoc2.proto.CoordinateProto size = 7;
      private com.lvl6.aoc2.proto.Coordiante.CoordinateProto size_ = com.lvl6.aoc2.proto.Coordiante.CoordinateProto.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.lvl6.aoc2.proto.Coordiante.CoordinateProto, com.lvl6.aoc2.proto.Coordiante.CoordinateProto.Builder, com.lvl6.aoc2.proto.Coordiante.CoordinateProtoOrBuilder> sizeBuilder_;
      /**
       * <code>optional .com.lvl6.aoc2.proto.CoordinateProto size = 7;</code>
       */
      public boolean hasSize() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional .com.lvl6.aoc2.proto.CoordinateProto size = 7;</code>
       */
      public com.lvl6.aoc2.proto.Coordiante.CoordinateProto getSize() {
        if (sizeBuilder_ == null) {
          return size_;
        } else {
          return sizeBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.lvl6.aoc2.proto.CoordinateProto size = 7;</code>
       */
      public Builder setSize(com.lvl6.aoc2.proto.Coordiante.CoordinateProto value) {
        if (sizeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          size_ = value;
          onChanged();
        } else {
          sizeBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000040;
        return this;
      }
      /**
       * <code>optional .com.lvl6.aoc2.proto.CoordinateProto size = 7;</code>
       */
      public Builder setSize(
          com.lvl6.aoc2.proto.Coordiante.CoordinateProto.Builder builderForValue) {
        if (sizeBuilder_ == null) {
          size_ = builderForValue.build();
          onChanged();
        } else {
          sizeBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000040;
        return this;
      }
      /**
       * <code>optional .com.lvl6.aoc2.proto.CoordinateProto size = 7;</code>
       */
      public Builder mergeSize(com.lvl6.aoc2.proto.Coordiante.CoordinateProto value) {
        if (sizeBuilder_ == null) {
          if (((bitField0_ & 0x00000040) == 0x00000040) &&
              size_ != com.lvl6.aoc2.proto.Coordiante.CoordinateProto.getDefaultInstance()) {
            size_ =
              com.lvl6.aoc2.proto.Coordiante.CoordinateProto.newBuilder(size_).mergeFrom(value).buildPartial();
          } else {
            size_ = value;
          }
          onChanged();
        } else {
          sizeBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000040;
        return this;
      }
      /**
       * <code>optional .com.lvl6.aoc2.proto.CoordinateProto size = 7;</code>
       */
      public Builder clearSize() {
        if (sizeBuilder_ == null) {
          size_ = com.lvl6.aoc2.proto.Coordiante.CoordinateProto.getDefaultInstance();
          onChanged();
        } else {
          sizeBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }
      /**
       * <code>optional .com.lvl6.aoc2.proto.CoordinateProto size = 7;</code>
       */
      public com.lvl6.aoc2.proto.Coordiante.CoordinateProto.Builder getSizeBuilder() {
        bitField0_ |= 0x00000040;
        onChanged();
        return getSizeFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.lvl6.aoc2.proto.CoordinateProto size = 7;</code>
       */
      public com.lvl6.aoc2.proto.Coordiante.CoordinateProtoOrBuilder getSizeOrBuilder() {
        if (sizeBuilder_ != null) {
          return sizeBuilder_.getMessageOrBuilder();
        } else {
          return size_;
        }
      }
      /**
       * <code>optional .com.lvl6.aoc2.proto.CoordinateProto size = 7;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.lvl6.aoc2.proto.Coordiante.CoordinateProto, com.lvl6.aoc2.proto.Coordiante.CoordinateProto.Builder, com.lvl6.aoc2.proto.Coordiante.CoordinateProtoOrBuilder> 
          getSizeFieldBuilder() {
        if (sizeBuilder_ == null) {
          sizeBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.lvl6.aoc2.proto.Coordiante.CoordinateProto, com.lvl6.aoc2.proto.Coordiante.CoordinateProto.Builder, com.lvl6.aoc2.proto.Coordiante.CoordinateProtoOrBuilder>(
                  size_,
                  getParentForChildren(),
                  isClean());
          size_ = null;
        }
        return sizeBuilder_;
      }

      // optional int32 buildSpeedUpBaseCost = 8;
      private int buildSpeedUpBaseCost_ ;
      /**
       * <code>optional int32 buildSpeedUpBaseCost = 8;</code>
       */
      public boolean hasBuildSpeedUpBaseCost() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional int32 buildSpeedUpBaseCost = 8;</code>
       */
      public int getBuildSpeedUpBaseCost() {
        return buildSpeedUpBaseCost_;
      }
      /**
       * <code>optional int32 buildSpeedUpBaseCost = 8;</code>
       */
      public Builder setBuildSpeedUpBaseCost(int value) {
        bitField0_ |= 0x00000080;
        buildSpeedUpBaseCost_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 buildSpeedUpBaseCost = 8;</code>
       */
      public Builder clearBuildSpeedUpBaseCost() {
        bitField0_ = (bitField0_ & ~0x00000080);
        buildSpeedUpBaseCost_ = 0;
        onChanged();
        return this;
      }

      // optional int32 functionValue = 9;
      private int functionValue_ ;
      /**
       * <code>optional int32 functionValue = 9;</code>
       */
      public boolean hasFunctionValue() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional int32 functionValue = 9;</code>
       */
      public int getFunctionValue() {
        return functionValue_;
      }
      /**
       * <code>optional int32 functionValue = 9;</code>
       */
      public Builder setFunctionValue(int value) {
        bitField0_ |= 0x00000100;
        functionValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 functionValue = 9;</code>
       */
      public Builder clearFunctionValue() {
        bitField0_ = (bitField0_ & ~0x00000100);
        functionValue_ = 0;
        onChanged();
        return this;
      }

      // required .com.lvl6.aoc2.proto.ResourceType functionResource = 10;
      private com.lvl6.aoc2.proto.ResourceEnum.ResourceType functionResource_ = com.lvl6.aoc2.proto.ResourceEnum.ResourceType.GOLD;
      /**
       * <code>required .com.lvl6.aoc2.proto.ResourceType functionResource = 10;</code>
       */
      public boolean hasFunctionResource() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>required .com.lvl6.aoc2.proto.ResourceType functionResource = 10;</code>
       */
      public com.lvl6.aoc2.proto.ResourceEnum.ResourceType getFunctionResource() {
        return functionResource_;
      }
      /**
       * <code>required .com.lvl6.aoc2.proto.ResourceType functionResource = 10;</code>
       */
      public Builder setFunctionResource(com.lvl6.aoc2.proto.ResourceEnum.ResourceType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000200;
        functionResource_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .com.lvl6.aoc2.proto.ResourceType functionResource = 10;</code>
       */
      public Builder clearFunctionResource() {
        bitField0_ = (bitField0_ & ~0x00000200);
        functionResource_ = com.lvl6.aoc2.proto.ResourceEnum.ResourceType.GOLD;
        onChanged();
        return this;
      }

      // optional int32 speedUpFunctionBaseCost = 11;
      private int speedUpFunctionBaseCost_ ;
      /**
       * <code>optional int32 speedUpFunctionBaseCost = 11;</code>
       */
      public boolean hasSpeedUpFunctionBaseCost() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <code>optional int32 speedUpFunctionBaseCost = 11;</code>
       */
      public int getSpeedUpFunctionBaseCost() {
        return speedUpFunctionBaseCost_;
      }
      /**
       * <code>optional int32 speedUpFunctionBaseCost = 11;</code>
       */
      public Builder setSpeedUpFunctionBaseCost(int value) {
        bitField0_ |= 0x00000400;
        speedUpFunctionBaseCost_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 speedUpFunctionBaseCost = 11;</code>
       */
      public Builder clearSpeedUpFunctionBaseCost() {
        bitField0_ = (bitField0_ & ~0x00000400);
        speedUpFunctionBaseCost_ = 0;
        onChanged();
        return this;
      }

      // optional int32 capacity = 12;
      private int capacity_ ;
      /**
       * <code>optional int32 capacity = 12;</code>
       */
      public boolean hasCapacity() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      /**
       * <code>optional int32 capacity = 12;</code>
       */
      public int getCapacity() {
        return capacity_;
      }
      /**
       * <code>optional int32 capacity = 12;</code>
       */
      public Builder setCapacity(int value) {
        bitField0_ |= 0x00000800;
        capacity_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 capacity = 12;</code>
       */
      public Builder clearCapacity() {
        bitField0_ = (bitField0_ & ~0x00000800);
        capacity_ = 0;
        onChanged();
        return this;
      }

      // optional int32 level = 13;
      private int level_ ;
      /**
       * <code>optional int32 level = 13;</code>
       */
      public boolean hasLevel() {
        return ((bitField0_ & 0x00001000) == 0x00001000);
      }
      /**
       * <code>optional int32 level = 13;</code>
       */
      public int getLevel() {
        return level_;
      }
      /**
       * <code>optional int32 level = 13;</code>
       */
      public Builder setLevel(int value) {
        bitField0_ |= 0x00001000;
        level_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 level = 13;</code>
       */
      public Builder clearLevel() {
        bitField0_ = (bitField0_ & ~0x00001000);
        level_ = 0;
        onChanged();
        return this;
      }

      // optional string name = 14;
      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 14;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00002000) == 0x00002000);
      }
      /**
       * <code>optional string name = 14;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 14;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 14;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00002000;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 14;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00002000);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 14;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00002000;
        name_ = value;
        onChanged();
        return this;
      }

      // optional string imageName = 15;
      private java.lang.Object imageName_ = "";
      /**
       * <code>optional string imageName = 15;</code>
       */
      public boolean hasImageName() {
        return ((bitField0_ & 0x00004000) == 0x00004000);
      }
      /**
       * <code>optional string imageName = 15;</code>
       */
      public java.lang.String getImageName() {
        java.lang.Object ref = imageName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          imageName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string imageName = 15;</code>
       */
      public com.google.protobuf.ByteString
          getImageNameBytes() {
        java.lang.Object ref = imageName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          imageName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string imageName = 15;</code>
       */
      public Builder setImageName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00004000;
        imageName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string imageName = 15;</code>
       */
      public Builder clearImageName() {
        bitField0_ = (bitField0_ & ~0x00004000);
        imageName_ = getDefaultInstance().getImageName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string imageName = 15;</code>
       */
      public Builder setImageNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00004000;
        imageName_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.lvl6.aoc2.proto.StructureProto)
    }

    static {
      defaultInstance = new StructureProto(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.lvl6.aoc2.proto.StructureProto)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lvl6_aoc2_proto_StructureProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_lvl6_aoc2_proto_StructureProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021StructProto.proto\022\023com.lvl6.aoc2.proto" +
      "\032\022ResourceType.proto\032\025CoordinateProto.pr" +
      "oto\"\353\004\n\016StructureProto\022\023\n\013structureID\030\001 " +
      "\001(\005\022G\n\010function\030\002 \001(\01625.com.lvl6.aoc2.pr" +
      "oto.StructureProto.StructureFunction\022\021\n\t" +
      "buildCost\030\003 \001(\005\022\021\n\tbuildTime\030\004 \001(\005\0228\n\rbu" +
      "ildResource\030\005 \002(\0162!.com.lvl6.aoc2.proto." +
      "ResourceType\022\034\n\024upgradeTownHallLevel\030\006 \001" +
      "(\005\0222\n\004size\030\007 \001(\0132$.com.lvl6.aoc2.proto.C" +
      "oordinateProto\022\034\n\024buildSpeedUpBaseCost\030\010",
      " \001(\005\022\025\n\rfunctionValue\030\t \001(\005\022;\n\020functionR" +
      "esource\030\n \002(\0162!.com.lvl6.aoc2.proto.Reso" +
      "urceType\022\037\n\027speedUpFunctionBaseCost\030\013 \001(" +
      "\005\022\020\n\010capacity\030\014 \001(\005\022\r\n\005level\030\r \001(\005\022\014\n\004na" +
      "me\030\016 \001(\t\022\021\n\timageName\030\017 \001(\t\"t\n\021Structure" +
      "Function\022\r\n\tTOWN_HALL\020\000\022\n\n\006INCOME\020\001\022\013\n\007S" +
      "TORAGE\020\002\022\016\n\nBLACKSMITH\020\003\022\013\n\007LIBRARY\020\004\022\n\n" +
      "\006FUSION\020\005\022\016\n\nDECORATION\020\006B\013B\tStructure"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_lvl6_aoc2_proto_StructureProto_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_lvl6_aoc2_proto_StructureProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_lvl6_aoc2_proto_StructureProto_descriptor,
              new java.lang.String[] { "StructureID", "Function", "BuildCost", "BuildTime", "BuildResource", "UpgradeTownHallLevel", "Size", "BuildSpeedUpBaseCost", "FunctionValue", "FunctionResource", "SpeedUpFunctionBaseCost", "Capacity", "Level", "Name", "ImageName", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.lvl6.aoc2.proto.ResourceEnum.getDescriptor(),
          com.lvl6.aoc2.proto.Coordiante.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
