// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LevelUpEvent.proto

package com.lvl6.aoc2.eventprotos;

public final class LevelUpEventProto {
  private LevelUpEventProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface LevelUpRequestProtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional .proto.MinimumUserProto mup = 1;
    boolean hasMup();
    com.lvl6.aoc2.noneventprotos.FullUser.MinimumUserProto getMup();
    com.lvl6.aoc2.noneventprotos.FullUser.MinimumUserProtoOrBuilder getMupOrBuilder();
  }
  public static final class LevelUpRequestProto extends
      com.google.protobuf.GeneratedMessage
      implements LevelUpRequestProtoOrBuilder {
    // Use LevelUpRequestProto.newBuilder() to construct.
    private LevelUpRequestProto(Builder builder) {
      super(builder);
    }
    private LevelUpRequestProto(boolean noInit) {}
    
    private static final LevelUpRequestProto defaultInstance;
    public static LevelUpRequestProto getDefaultInstance() {
      return defaultInstance;
    }
    
    public LevelUpRequestProto getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lvl6.aoc2.eventprotos.LevelUpEventProto.internal_static_proto_LevelUpRequestProto_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lvl6.aoc2.eventprotos.LevelUpEventProto.internal_static_proto_LevelUpRequestProto_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional .proto.MinimumUserProto mup = 1;
    public static final int MUP_FIELD_NUMBER = 1;
    private com.lvl6.aoc2.noneventprotos.FullUser.MinimumUserProto mup_;
    public boolean hasMup() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public com.lvl6.aoc2.noneventprotos.FullUser.MinimumUserProto getMup() {
      return mup_;
    }
    public com.lvl6.aoc2.noneventprotos.FullUser.MinimumUserProtoOrBuilder getMupOrBuilder() {
      return mup_;
    }
    
    private void initFields() {
      mup_ = com.lvl6.aoc2.noneventprotos.FullUser.MinimumUserProto.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, mup_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, mup_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.lvl6.aoc2.eventprotos.LevelUpEventProto.LevelUpRequestProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.lvl6.aoc2.eventprotos.LevelUpEventProto.LevelUpRequestProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.lvl6.aoc2.eventprotos.LevelUpEventProto.LevelUpRequestProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.lvl6.aoc2.eventprotos.LevelUpEventProto.LevelUpRequestProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.lvl6.aoc2.eventprotos.LevelUpEventProto.LevelUpRequestProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.lvl6.aoc2.eventprotos.LevelUpEventProto.LevelUpRequestProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.lvl6.aoc2.eventprotos.LevelUpEventProto.LevelUpRequestProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.lvl6.aoc2.eventprotos.LevelUpEventProto.LevelUpRequestProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.lvl6.aoc2.eventprotos.LevelUpEventProto.LevelUpRequestProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.lvl6.aoc2.eventprotos.LevelUpEventProto.LevelUpRequestProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.lvl6.aoc2.eventprotos.LevelUpEventProto.LevelUpRequestProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.lvl6.aoc2.eventprotos.LevelUpEventProto.LevelUpRequestProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.lvl6.aoc2.eventprotos.LevelUpEventProto.internal_static_proto_LevelUpRequestProto_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.lvl6.aoc2.eventprotos.LevelUpEventProto.internal_static_proto_LevelUpRequestProto_fieldAccessorTable;
      }
      
      // Construct using com.lvl6.aoc2.eventprotos.LevelUpEventProto.LevelUpRequestProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getMupFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (mupBuilder_ == null) {
          mup_ = com.lvl6.aoc2.noneventprotos.FullUser.MinimumUserProto.getDefaultInstance();
        } else {
          mupBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.lvl6.aoc2.eventprotos.LevelUpEventProto.LevelUpRequestProto.getDescriptor();
      }
      
      public com.lvl6.aoc2.eventprotos.LevelUpEventProto.LevelUpRequestProto getDefaultInstanceForType() {
        return com.lvl6.aoc2.eventprotos.LevelUpEventProto.LevelUpRequestProto.getDefaultInstance();
      }
      
      public com.lvl6.aoc2.eventprotos.LevelUpEventProto.LevelUpRequestProto build() {
        com.lvl6.aoc2.eventprotos.LevelUpEventProto.LevelUpRequestProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.lvl6.aoc2.eventprotos.LevelUpEventProto.LevelUpRequestProto buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.lvl6.aoc2.eventprotos.LevelUpEventProto.LevelUpRequestProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.lvl6.aoc2.eventprotos.LevelUpEventProto.LevelUpRequestProto buildPartial() {
        com.lvl6.aoc2.eventprotos.LevelUpEventProto.LevelUpRequestProto result = new com.lvl6.aoc2.eventprotos.LevelUpEventProto.LevelUpRequestProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (mupBuilder_ == null) {
          result.mup_ = mup_;
        } else {
          result.mup_ = mupBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.lvl6.aoc2.eventprotos.LevelUpEventProto.LevelUpRequestProto) {
          return mergeFrom((com.lvl6.aoc2.eventprotos.LevelUpEventProto.LevelUpRequestProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.lvl6.aoc2.eventprotos.LevelUpEventProto.LevelUpRequestProto other) {
        if (other == com.lvl6.aoc2.eventprotos.LevelUpEventProto.LevelUpRequestProto.getDefaultInstance()) return this;
        if (other.hasMup()) {
          mergeMup(other.getMup());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              com.lvl6.aoc2.noneventprotos.FullUser.MinimumUserProto.Builder subBuilder = com.lvl6.aoc2.noneventprotos.FullUser.MinimumUserProto.newBuilder();
              if (hasMup()) {
                subBuilder.mergeFrom(getMup());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setMup(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional .proto.MinimumUserProto mup = 1;
      private com.lvl6.aoc2.noneventprotos.FullUser.MinimumUserProto mup_ = com.lvl6.aoc2.noneventprotos.FullUser.MinimumUserProto.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.lvl6.aoc2.noneventprotos.FullUser.MinimumUserProto, com.lvl6.aoc2.noneventprotos.FullUser.MinimumUserProto.Builder, com.lvl6.aoc2.noneventprotos.FullUser.MinimumUserProtoOrBuilder> mupBuilder_;
      public boolean hasMup() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public com.lvl6.aoc2.noneventprotos.FullUser.MinimumUserProto getMup() {
        if (mupBuilder_ == null) {
          return mup_;
        } else {
          return mupBuilder_.getMessage();
        }
      }
      public Builder setMup(com.lvl6.aoc2.noneventprotos.FullUser.MinimumUserProto value) {
        if (mupBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          mup_ = value;
          onChanged();
        } else {
          mupBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder setMup(
          com.lvl6.aoc2.noneventprotos.FullUser.MinimumUserProto.Builder builderForValue) {
        if (mupBuilder_ == null) {
          mup_ = builderForValue.build();
          onChanged();
        } else {
          mupBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder mergeMup(com.lvl6.aoc2.noneventprotos.FullUser.MinimumUserProto value) {
        if (mupBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              mup_ != com.lvl6.aoc2.noneventprotos.FullUser.MinimumUserProto.getDefaultInstance()) {
            mup_ =
              com.lvl6.aoc2.noneventprotos.FullUser.MinimumUserProto.newBuilder(mup_).mergeFrom(value).buildPartial();
          } else {
            mup_ = value;
          }
          onChanged();
        } else {
          mupBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder clearMup() {
        if (mupBuilder_ == null) {
          mup_ = com.lvl6.aoc2.noneventprotos.FullUser.MinimumUserProto.getDefaultInstance();
          onChanged();
        } else {
          mupBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      public com.lvl6.aoc2.noneventprotos.FullUser.MinimumUserProto.Builder getMupBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getMupFieldBuilder().getBuilder();
      }
      public com.lvl6.aoc2.noneventprotos.FullUser.MinimumUserProtoOrBuilder getMupOrBuilder() {
        if (mupBuilder_ != null) {
          return mupBuilder_.getMessageOrBuilder();
        } else {
          return mup_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          com.lvl6.aoc2.noneventprotos.FullUser.MinimumUserProto, com.lvl6.aoc2.noneventprotos.FullUser.MinimumUserProto.Builder, com.lvl6.aoc2.noneventprotos.FullUser.MinimumUserProtoOrBuilder> 
          getMupFieldBuilder() {
        if (mupBuilder_ == null) {
          mupBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.lvl6.aoc2.noneventprotos.FullUser.MinimumUserProto, com.lvl6.aoc2.noneventprotos.FullUser.MinimumUserProto.Builder, com.lvl6.aoc2.noneventprotos.FullUser.MinimumUserProtoOrBuilder>(
                  mup_,
                  getParentForChildren(),
                  isClean());
          mup_ = null;
        }
        return mupBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:proto.LevelUpRequestProto)
    }
    
    static {
      defaultInstance = new LevelUpRequestProto(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:proto.LevelUpRequestProto)
  }
  
  public interface LevelUpResponseProtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional .proto.MinimumUserProto mup = 1;
    boolean hasMup();
    com.lvl6.aoc2.noneventprotos.FullUser.MinimumUserProto getMup();
    com.lvl6.aoc2.noneventprotos.FullUser.MinimumUserProtoOrBuilder getMupOrBuilder();
    
    // optional .proto.LevelUpResponseProto.LevelUpStatus status = 2;
    boolean hasStatus();
    com.lvl6.aoc2.eventprotos.LevelUpEventProto.LevelUpResponseProto.LevelUpStatus getStatus();
    
    // optional int32 newLevel = 3;
    boolean hasNewLevel();
    int getNewLevel();
    
    // optional int32 newNextLevel = 4;
    boolean hasNewNextLevel();
    int getNewNextLevel();
    
    // optional int32 experienceRequiredForNewNextLevel = 5;
    boolean hasExperienceRequiredForNewNextLevel();
    int getExperienceRequiredForNewNextLevel();
    
    // optional int32 newHp = 8;
    boolean hasNewHp();
    int getNewHp();
    
    // optional int32 newMana = 9;
    boolean hasNewMana();
    int getNewMana();
    
    // optional int32 newAttack = 10;
    boolean hasNewAttack();
    int getNewAttack();
    
    // optional int32 newDefense = 11;
    boolean hasNewDefense();
    int getNewDefense();
  }
  public static final class LevelUpResponseProto extends
      com.google.protobuf.GeneratedMessage
      implements LevelUpResponseProtoOrBuilder {
    // Use LevelUpResponseProto.newBuilder() to construct.
    private LevelUpResponseProto(Builder builder) {
      super(builder);
    }
    private LevelUpResponseProto(boolean noInit) {}
    
    private static final LevelUpResponseProto defaultInstance;
    public static LevelUpResponseProto getDefaultInstance() {
      return defaultInstance;
    }
    
    public LevelUpResponseProto getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lvl6.aoc2.eventprotos.LevelUpEventProto.internal_static_proto_LevelUpResponseProto_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lvl6.aoc2.eventprotos.LevelUpEventProto.internal_static_proto_LevelUpResponseProto_fieldAccessorTable;
    }
    
    public enum LevelUpStatus
        implements com.google.protobuf.ProtocolMessageEnum {
      SUCCESS(0, 0),
      FAIL_NOT_ENOUGH_EXP(1, 1),
      FAIL_ALREADY_AT_MAX_LEVEL(2, 2),
      FAIL_OTHER(3, 3),
      ;
      
      public static final int SUCCESS_VALUE = 0;
      public static final int FAIL_NOT_ENOUGH_EXP_VALUE = 1;
      public static final int FAIL_ALREADY_AT_MAX_LEVEL_VALUE = 2;
      public static final int FAIL_OTHER_VALUE = 3;
      
      
      public final int getNumber() { return value; }
      
      public static LevelUpStatus valueOf(int value) {
        switch (value) {
          case 0: return SUCCESS;
          case 1: return FAIL_NOT_ENOUGH_EXP;
          case 2: return FAIL_ALREADY_AT_MAX_LEVEL;
          case 3: return FAIL_OTHER;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<LevelUpStatus>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<LevelUpStatus>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<LevelUpStatus>() {
              public LevelUpStatus findValueByNumber(int number) {
                return LevelUpStatus.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.lvl6.aoc2.eventprotos.LevelUpEventProto.LevelUpResponseProto.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final LevelUpStatus[] VALUES = {
        SUCCESS, FAIL_NOT_ENOUGH_EXP, FAIL_ALREADY_AT_MAX_LEVEL, FAIL_OTHER, 
      };
      
      public static LevelUpStatus valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private LevelUpStatus(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:proto.LevelUpResponseProto.LevelUpStatus)
    }
    
    private int bitField0_;
    // optional .proto.MinimumUserProto mup = 1;
    public static final int MUP_FIELD_NUMBER = 1;
    private com.lvl6.aoc2.noneventprotos.FullUser.MinimumUserProto mup_;
    public boolean hasMup() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public com.lvl6.aoc2.noneventprotos.FullUser.MinimumUserProto getMup() {
      return mup_;
    }
    public com.lvl6.aoc2.noneventprotos.FullUser.MinimumUserProtoOrBuilder getMupOrBuilder() {
      return mup_;
    }
    
    // optional .proto.LevelUpResponseProto.LevelUpStatus status = 2;
    public static final int STATUS_FIELD_NUMBER = 2;
    private com.lvl6.aoc2.eventprotos.LevelUpEventProto.LevelUpResponseProto.LevelUpStatus status_;
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public com.lvl6.aoc2.eventprotos.LevelUpEventProto.LevelUpResponseProto.LevelUpStatus getStatus() {
      return status_;
    }
    
    // optional int32 newLevel = 3;
    public static final int NEWLEVEL_FIELD_NUMBER = 3;
    private int newLevel_;
    public boolean hasNewLevel() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getNewLevel() {
      return newLevel_;
    }
    
    // optional int32 newNextLevel = 4;
    public static final int NEWNEXTLEVEL_FIELD_NUMBER = 4;
    private int newNextLevel_;
    public boolean hasNewNextLevel() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public int getNewNextLevel() {
      return newNextLevel_;
    }
    
    // optional int32 experienceRequiredForNewNextLevel = 5;
    public static final int EXPERIENCEREQUIREDFORNEWNEXTLEVEL_FIELD_NUMBER = 5;
    private int experienceRequiredForNewNextLevel_;
    public boolean hasExperienceRequiredForNewNextLevel() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public int getExperienceRequiredForNewNextLevel() {
      return experienceRequiredForNewNextLevel_;
    }
    
    // optional int32 newHp = 8;
    public static final int NEWHP_FIELD_NUMBER = 8;
    private int newHp_;
    public boolean hasNewHp() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public int getNewHp() {
      return newHp_;
    }
    
    // optional int32 newMana = 9;
    public static final int NEWMANA_FIELD_NUMBER = 9;
    private int newMana_;
    public boolean hasNewMana() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public int getNewMana() {
      return newMana_;
    }
    
    // optional int32 newAttack = 10;
    public static final int NEWATTACK_FIELD_NUMBER = 10;
    private int newAttack_;
    public boolean hasNewAttack() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    public int getNewAttack() {
      return newAttack_;
    }
    
    // optional int32 newDefense = 11;
    public static final int NEWDEFENSE_FIELD_NUMBER = 11;
    private int newDefense_;
    public boolean hasNewDefense() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    public int getNewDefense() {
      return newDefense_;
    }
    
    private void initFields() {
      mup_ = com.lvl6.aoc2.noneventprotos.FullUser.MinimumUserProto.getDefaultInstance();
      status_ = com.lvl6.aoc2.eventprotos.LevelUpEventProto.LevelUpResponseProto.LevelUpStatus.SUCCESS;
      newLevel_ = 0;
      newNextLevel_ = 0;
      experienceRequiredForNewNextLevel_ = 0;
      newHp_ = 0;
      newMana_ = 0;
      newAttack_ = 0;
      newDefense_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, mup_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, status_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, newLevel_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, newNextLevel_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, experienceRequiredForNewNextLevel_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(8, newHp_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt32(9, newMana_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeInt32(10, newAttack_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeInt32(11, newDefense_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, mup_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, status_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, newLevel_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, newNextLevel_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, experienceRequiredForNewNextLevel_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, newHp_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, newMana_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(10, newAttack_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(11, newDefense_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.lvl6.aoc2.eventprotos.LevelUpEventProto.LevelUpResponseProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.lvl6.aoc2.eventprotos.LevelUpEventProto.LevelUpResponseProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.lvl6.aoc2.eventprotos.LevelUpEventProto.LevelUpResponseProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.lvl6.aoc2.eventprotos.LevelUpEventProto.LevelUpResponseProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.lvl6.aoc2.eventprotos.LevelUpEventProto.LevelUpResponseProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.lvl6.aoc2.eventprotos.LevelUpEventProto.LevelUpResponseProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.lvl6.aoc2.eventprotos.LevelUpEventProto.LevelUpResponseProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.lvl6.aoc2.eventprotos.LevelUpEventProto.LevelUpResponseProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.lvl6.aoc2.eventprotos.LevelUpEventProto.LevelUpResponseProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.lvl6.aoc2.eventprotos.LevelUpEventProto.LevelUpResponseProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.lvl6.aoc2.eventprotos.LevelUpEventProto.LevelUpResponseProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.lvl6.aoc2.eventprotos.LevelUpEventProto.LevelUpResponseProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.lvl6.aoc2.eventprotos.LevelUpEventProto.internal_static_proto_LevelUpResponseProto_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.lvl6.aoc2.eventprotos.LevelUpEventProto.internal_static_proto_LevelUpResponseProto_fieldAccessorTable;
      }
      
      // Construct using com.lvl6.aoc2.eventprotos.LevelUpEventProto.LevelUpResponseProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getMupFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (mupBuilder_ == null) {
          mup_ = com.lvl6.aoc2.noneventprotos.FullUser.MinimumUserProto.getDefaultInstance();
        } else {
          mupBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        status_ = com.lvl6.aoc2.eventprotos.LevelUpEventProto.LevelUpResponseProto.LevelUpStatus.SUCCESS;
        bitField0_ = (bitField0_ & ~0x00000002);
        newLevel_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        newNextLevel_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        experienceRequiredForNewNextLevel_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        newHp_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        newMana_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        newAttack_ = 0;
        bitField0_ = (bitField0_ & ~0x00000080);
        newDefense_ = 0;
        bitField0_ = (bitField0_ & ~0x00000100);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.lvl6.aoc2.eventprotos.LevelUpEventProto.LevelUpResponseProto.getDescriptor();
      }
      
      public com.lvl6.aoc2.eventprotos.LevelUpEventProto.LevelUpResponseProto getDefaultInstanceForType() {
        return com.lvl6.aoc2.eventprotos.LevelUpEventProto.LevelUpResponseProto.getDefaultInstance();
      }
      
      public com.lvl6.aoc2.eventprotos.LevelUpEventProto.LevelUpResponseProto build() {
        com.lvl6.aoc2.eventprotos.LevelUpEventProto.LevelUpResponseProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.lvl6.aoc2.eventprotos.LevelUpEventProto.LevelUpResponseProto buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.lvl6.aoc2.eventprotos.LevelUpEventProto.LevelUpResponseProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.lvl6.aoc2.eventprotos.LevelUpEventProto.LevelUpResponseProto buildPartial() {
        com.lvl6.aoc2.eventprotos.LevelUpEventProto.LevelUpResponseProto result = new com.lvl6.aoc2.eventprotos.LevelUpEventProto.LevelUpResponseProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (mupBuilder_ == null) {
          result.mup_ = mup_;
        } else {
          result.mup_ = mupBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.status_ = status_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.newLevel_ = newLevel_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.newNextLevel_ = newNextLevel_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.experienceRequiredForNewNextLevel_ = experienceRequiredForNewNextLevel_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.newHp_ = newHp_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.newMana_ = newMana_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.newAttack_ = newAttack_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.newDefense_ = newDefense_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.lvl6.aoc2.eventprotos.LevelUpEventProto.LevelUpResponseProto) {
          return mergeFrom((com.lvl6.aoc2.eventprotos.LevelUpEventProto.LevelUpResponseProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.lvl6.aoc2.eventprotos.LevelUpEventProto.LevelUpResponseProto other) {
        if (other == com.lvl6.aoc2.eventprotos.LevelUpEventProto.LevelUpResponseProto.getDefaultInstance()) return this;
        if (other.hasMup()) {
          mergeMup(other.getMup());
        }
        if (other.hasStatus()) {
          setStatus(other.getStatus());
        }
        if (other.hasNewLevel()) {
          setNewLevel(other.getNewLevel());
        }
        if (other.hasNewNextLevel()) {
          setNewNextLevel(other.getNewNextLevel());
        }
        if (other.hasExperienceRequiredForNewNextLevel()) {
          setExperienceRequiredForNewNextLevel(other.getExperienceRequiredForNewNextLevel());
        }
        if (other.hasNewHp()) {
          setNewHp(other.getNewHp());
        }
        if (other.hasNewMana()) {
          setNewMana(other.getNewMana());
        }
        if (other.hasNewAttack()) {
          setNewAttack(other.getNewAttack());
        }
        if (other.hasNewDefense()) {
          setNewDefense(other.getNewDefense());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              com.lvl6.aoc2.noneventprotos.FullUser.MinimumUserProto.Builder subBuilder = com.lvl6.aoc2.noneventprotos.FullUser.MinimumUserProto.newBuilder();
              if (hasMup()) {
                subBuilder.mergeFrom(getMup());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setMup(subBuilder.buildPartial());
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              com.lvl6.aoc2.eventprotos.LevelUpEventProto.LevelUpResponseProto.LevelUpStatus value = com.lvl6.aoc2.eventprotos.LevelUpEventProto.LevelUpResponseProto.LevelUpStatus.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                status_ = value;
              }
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              newLevel_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              newNextLevel_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              experienceRequiredForNewNextLevel_ = input.readInt32();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000020;
              newHp_ = input.readInt32();
              break;
            }
            case 72: {
              bitField0_ |= 0x00000040;
              newMana_ = input.readInt32();
              break;
            }
            case 80: {
              bitField0_ |= 0x00000080;
              newAttack_ = input.readInt32();
              break;
            }
            case 88: {
              bitField0_ |= 0x00000100;
              newDefense_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional .proto.MinimumUserProto mup = 1;
      private com.lvl6.aoc2.noneventprotos.FullUser.MinimumUserProto mup_ = com.lvl6.aoc2.noneventprotos.FullUser.MinimumUserProto.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.lvl6.aoc2.noneventprotos.FullUser.MinimumUserProto, com.lvl6.aoc2.noneventprotos.FullUser.MinimumUserProto.Builder, com.lvl6.aoc2.noneventprotos.FullUser.MinimumUserProtoOrBuilder> mupBuilder_;
      public boolean hasMup() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public com.lvl6.aoc2.noneventprotos.FullUser.MinimumUserProto getMup() {
        if (mupBuilder_ == null) {
          return mup_;
        } else {
          return mupBuilder_.getMessage();
        }
      }
      public Builder setMup(com.lvl6.aoc2.noneventprotos.FullUser.MinimumUserProto value) {
        if (mupBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          mup_ = value;
          onChanged();
        } else {
          mupBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder setMup(
          com.lvl6.aoc2.noneventprotos.FullUser.MinimumUserProto.Builder builderForValue) {
        if (mupBuilder_ == null) {
          mup_ = builderForValue.build();
          onChanged();
        } else {
          mupBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder mergeMup(com.lvl6.aoc2.noneventprotos.FullUser.MinimumUserProto value) {
        if (mupBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              mup_ != com.lvl6.aoc2.noneventprotos.FullUser.MinimumUserProto.getDefaultInstance()) {
            mup_ =
              com.lvl6.aoc2.noneventprotos.FullUser.MinimumUserProto.newBuilder(mup_).mergeFrom(value).buildPartial();
          } else {
            mup_ = value;
          }
          onChanged();
        } else {
          mupBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder clearMup() {
        if (mupBuilder_ == null) {
          mup_ = com.lvl6.aoc2.noneventprotos.FullUser.MinimumUserProto.getDefaultInstance();
          onChanged();
        } else {
          mupBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      public com.lvl6.aoc2.noneventprotos.FullUser.MinimumUserProto.Builder getMupBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getMupFieldBuilder().getBuilder();
      }
      public com.lvl6.aoc2.noneventprotos.FullUser.MinimumUserProtoOrBuilder getMupOrBuilder() {
        if (mupBuilder_ != null) {
          return mupBuilder_.getMessageOrBuilder();
        } else {
          return mup_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          com.lvl6.aoc2.noneventprotos.FullUser.MinimumUserProto, com.lvl6.aoc2.noneventprotos.FullUser.MinimumUserProto.Builder, com.lvl6.aoc2.noneventprotos.FullUser.MinimumUserProtoOrBuilder> 
          getMupFieldBuilder() {
        if (mupBuilder_ == null) {
          mupBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.lvl6.aoc2.noneventprotos.FullUser.MinimumUserProto, com.lvl6.aoc2.noneventprotos.FullUser.MinimumUserProto.Builder, com.lvl6.aoc2.noneventprotos.FullUser.MinimumUserProtoOrBuilder>(
                  mup_,
                  getParentForChildren(),
                  isClean());
          mup_ = null;
        }
        return mupBuilder_;
      }
      
      // optional .proto.LevelUpResponseProto.LevelUpStatus status = 2;
      private com.lvl6.aoc2.eventprotos.LevelUpEventProto.LevelUpResponseProto.LevelUpStatus status_ = com.lvl6.aoc2.eventprotos.LevelUpEventProto.LevelUpResponseProto.LevelUpStatus.SUCCESS;
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public com.lvl6.aoc2.eventprotos.LevelUpEventProto.LevelUpResponseProto.LevelUpStatus getStatus() {
        return status_;
      }
      public Builder setStatus(com.lvl6.aoc2.eventprotos.LevelUpEventProto.LevelUpResponseProto.LevelUpStatus value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        status_ = value;
        onChanged();
        return this;
      }
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000002);
        status_ = com.lvl6.aoc2.eventprotos.LevelUpEventProto.LevelUpResponseProto.LevelUpStatus.SUCCESS;
        onChanged();
        return this;
      }
      
      // optional int32 newLevel = 3;
      private int newLevel_ ;
      public boolean hasNewLevel() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getNewLevel() {
        return newLevel_;
      }
      public Builder setNewLevel(int value) {
        bitField0_ |= 0x00000004;
        newLevel_ = value;
        onChanged();
        return this;
      }
      public Builder clearNewLevel() {
        bitField0_ = (bitField0_ & ~0x00000004);
        newLevel_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 newNextLevel = 4;
      private int newNextLevel_ ;
      public boolean hasNewNextLevel() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public int getNewNextLevel() {
        return newNextLevel_;
      }
      public Builder setNewNextLevel(int value) {
        bitField0_ |= 0x00000008;
        newNextLevel_ = value;
        onChanged();
        return this;
      }
      public Builder clearNewNextLevel() {
        bitField0_ = (bitField0_ & ~0x00000008);
        newNextLevel_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 experienceRequiredForNewNextLevel = 5;
      private int experienceRequiredForNewNextLevel_ ;
      public boolean hasExperienceRequiredForNewNextLevel() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public int getExperienceRequiredForNewNextLevel() {
        return experienceRequiredForNewNextLevel_;
      }
      public Builder setExperienceRequiredForNewNextLevel(int value) {
        bitField0_ |= 0x00000010;
        experienceRequiredForNewNextLevel_ = value;
        onChanged();
        return this;
      }
      public Builder clearExperienceRequiredForNewNextLevel() {
        bitField0_ = (bitField0_ & ~0x00000010);
        experienceRequiredForNewNextLevel_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 newHp = 8;
      private int newHp_ ;
      public boolean hasNewHp() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public int getNewHp() {
        return newHp_;
      }
      public Builder setNewHp(int value) {
        bitField0_ |= 0x00000020;
        newHp_ = value;
        onChanged();
        return this;
      }
      public Builder clearNewHp() {
        bitField0_ = (bitField0_ & ~0x00000020);
        newHp_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 newMana = 9;
      private int newMana_ ;
      public boolean hasNewMana() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public int getNewMana() {
        return newMana_;
      }
      public Builder setNewMana(int value) {
        bitField0_ |= 0x00000040;
        newMana_ = value;
        onChanged();
        return this;
      }
      public Builder clearNewMana() {
        bitField0_ = (bitField0_ & ~0x00000040);
        newMana_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 newAttack = 10;
      private int newAttack_ ;
      public boolean hasNewAttack() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      public int getNewAttack() {
        return newAttack_;
      }
      public Builder setNewAttack(int value) {
        bitField0_ |= 0x00000080;
        newAttack_ = value;
        onChanged();
        return this;
      }
      public Builder clearNewAttack() {
        bitField0_ = (bitField0_ & ~0x00000080);
        newAttack_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 newDefense = 11;
      private int newDefense_ ;
      public boolean hasNewDefense() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      public int getNewDefense() {
        return newDefense_;
      }
      public Builder setNewDefense(int value) {
        bitField0_ |= 0x00000100;
        newDefense_ = value;
        onChanged();
        return this;
      }
      public Builder clearNewDefense() {
        bitField0_ = (bitField0_ & ~0x00000100);
        newDefense_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:proto.LevelUpResponseProto)
    }
    
    static {
      defaultInstance = new LevelUpResponseProto(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:proto.LevelUpResponseProto)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_LevelUpRequestProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_LevelUpRequestProto_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_LevelUpResponseProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_LevelUpResponseProto_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022LevelUpEvent.proto\022\005proto\032\023FullUserPro" +
      "to.proto\";\n\023LevelUpRequestProto\022$\n\003mup\030\001" +
      " \001(\0132\027.proto.MinimumUserProto\"\367\002\n\024LevelU" +
      "pResponseProto\022$\n\003mup\030\001 \001(\0132\027.proto.Mini" +
      "mumUserProto\0229\n\006status\030\002 \001(\0162).proto.Lev" +
      "elUpResponseProto.LevelUpStatus\022\020\n\010newLe" +
      "vel\030\003 \001(\005\022\024\n\014newNextLevel\030\004 \001(\005\022)\n!exper" +
      "ienceRequiredForNewNextLevel\030\005 \001(\005\022\r\n\005ne" +
      "wHp\030\010 \001(\005\022\017\n\007newMana\030\t \001(\005\022\021\n\tnewAttack\030" +
      "\n \001(\005\022\022\n\nnewDefense\030\013 \001(\005\"d\n\rLevelUpStat",
      "us\022\013\n\007SUCCESS\020\000\022\027\n\023FAIL_NOT_ENOUGH_EXP\020\001" +
      "\022\035\n\031FAIL_ALREADY_AT_MAX_LEVEL\020\002\022\016\n\nFAIL_" +
      "OTHER\020\003B.\n\031com.lvl6.aoc2.eventprotosB\021Le" +
      "velUpEventProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_proto_LevelUpRequestProto_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_proto_LevelUpRequestProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_proto_LevelUpRequestProto_descriptor,
              new java.lang.String[] { "Mup", },
              com.lvl6.aoc2.eventprotos.LevelUpEventProto.LevelUpRequestProto.class,
              com.lvl6.aoc2.eventprotos.LevelUpEventProto.LevelUpRequestProto.Builder.class);
          internal_static_proto_LevelUpResponseProto_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_proto_LevelUpResponseProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_proto_LevelUpResponseProto_descriptor,
              new java.lang.String[] { "Mup", "Status", "NewLevel", "NewNextLevel", "ExperienceRequiredForNewNextLevel", "NewHp", "NewMana", "NewAttack", "NewDefense", },
              com.lvl6.aoc2.eventprotos.LevelUpEventProto.LevelUpResponseProto.class,
              com.lvl6.aoc2.eventprotos.LevelUpEventProto.LevelUpResponseProto.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.lvl6.aoc2.noneventprotos.FullUser.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
