// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserConsumablesProto.proto

package com.lvl6.aoc2.noneventprotos;

public final class UserConsumable {
  private UserConsumable() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface UserConsumablesProtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional int32 userID = 1;
    boolean hasUserID();
    int getUserID();
    
    // optional int32 consumeableID = 2;
    boolean hasConsumeableID();
    int getConsumeableID();
    
    // optional int32 quantity = 3;
    boolean hasQuantity();
    int getQuantity();
  }
  public static final class UserConsumablesProto extends
      com.google.protobuf.GeneratedMessage
      implements UserConsumablesProtoOrBuilder {
    // Use UserConsumablesProto.newBuilder() to construct.
    private UserConsumablesProto(Builder builder) {
      super(builder);
    }
    private UserConsumablesProto(boolean noInit) {}
    
    private static final UserConsumablesProto defaultInstance;
    public static UserConsumablesProto getDefaultInstance() {
      return defaultInstance;
    }
    
    public UserConsumablesProto getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lvl6.aoc2.noneventprotos.UserConsumable.internal_static_proto_UserConsumablesProto_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lvl6.aoc2.noneventprotos.UserConsumable.internal_static_proto_UserConsumablesProto_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional int32 userID = 1;
    public static final int USERID_FIELD_NUMBER = 1;
    private int userID_;
    public boolean hasUserID() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getUserID() {
      return userID_;
    }
    
    // optional int32 consumeableID = 2;
    public static final int CONSUMEABLEID_FIELD_NUMBER = 2;
    private int consumeableID_;
    public boolean hasConsumeableID() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getConsumeableID() {
      return consumeableID_;
    }
    
    // optional int32 quantity = 3;
    public static final int QUANTITY_FIELD_NUMBER = 3;
    private int quantity_;
    public boolean hasQuantity() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getQuantity() {
      return quantity_;
    }
    
    private void initFields() {
      userID_ = 0;
      consumeableID_ = 0;
      quantity_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, userID_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, consumeableID_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, quantity_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, userID_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, consumeableID_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, quantity_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.lvl6.aoc2.noneventprotos.UserConsumable.UserConsumablesProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.lvl6.aoc2.noneventprotos.UserConsumable.UserConsumablesProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.lvl6.aoc2.noneventprotos.UserConsumable.UserConsumablesProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.lvl6.aoc2.noneventprotos.UserConsumable.UserConsumablesProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.lvl6.aoc2.noneventprotos.UserConsumable.UserConsumablesProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.lvl6.aoc2.noneventprotos.UserConsumable.UserConsumablesProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.lvl6.aoc2.noneventprotos.UserConsumable.UserConsumablesProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.lvl6.aoc2.noneventprotos.UserConsumable.UserConsumablesProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.lvl6.aoc2.noneventprotos.UserConsumable.UserConsumablesProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.lvl6.aoc2.noneventprotos.UserConsumable.UserConsumablesProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.lvl6.aoc2.noneventprotos.UserConsumable.UserConsumablesProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.lvl6.aoc2.noneventprotos.UserConsumable.UserConsumablesProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.lvl6.aoc2.noneventprotos.UserConsumable.internal_static_proto_UserConsumablesProto_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.lvl6.aoc2.noneventprotos.UserConsumable.internal_static_proto_UserConsumablesProto_fieldAccessorTable;
      }
      
      // Construct using com.lvl6.aoc2.noneventprotos.UserConsumable.UserConsumablesProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        userID_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        consumeableID_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        quantity_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.lvl6.aoc2.noneventprotos.UserConsumable.UserConsumablesProto.getDescriptor();
      }
      
      public com.lvl6.aoc2.noneventprotos.UserConsumable.UserConsumablesProto getDefaultInstanceForType() {
        return com.lvl6.aoc2.noneventprotos.UserConsumable.UserConsumablesProto.getDefaultInstance();
      }
      
      public com.lvl6.aoc2.noneventprotos.UserConsumable.UserConsumablesProto build() {
        com.lvl6.aoc2.noneventprotos.UserConsumable.UserConsumablesProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.lvl6.aoc2.noneventprotos.UserConsumable.UserConsumablesProto buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.lvl6.aoc2.noneventprotos.UserConsumable.UserConsumablesProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.lvl6.aoc2.noneventprotos.UserConsumable.UserConsumablesProto buildPartial() {
        com.lvl6.aoc2.noneventprotos.UserConsumable.UserConsumablesProto result = new com.lvl6.aoc2.noneventprotos.UserConsumable.UserConsumablesProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.userID_ = userID_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.consumeableID_ = consumeableID_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.quantity_ = quantity_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.lvl6.aoc2.noneventprotos.UserConsumable.UserConsumablesProto) {
          return mergeFrom((com.lvl6.aoc2.noneventprotos.UserConsumable.UserConsumablesProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.lvl6.aoc2.noneventprotos.UserConsumable.UserConsumablesProto other) {
        if (other == com.lvl6.aoc2.noneventprotos.UserConsumable.UserConsumablesProto.getDefaultInstance()) return this;
        if (other.hasUserID()) {
          setUserID(other.getUserID());
        }
        if (other.hasConsumeableID()) {
          setConsumeableID(other.getConsumeableID());
        }
        if (other.hasQuantity()) {
          setQuantity(other.getQuantity());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              userID_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              consumeableID_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              quantity_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional int32 userID = 1;
      private int userID_ ;
      public boolean hasUserID() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getUserID() {
        return userID_;
      }
      public Builder setUserID(int value) {
        bitField0_ |= 0x00000001;
        userID_ = value;
        onChanged();
        return this;
      }
      public Builder clearUserID() {
        bitField0_ = (bitField0_ & ~0x00000001);
        userID_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 consumeableID = 2;
      private int consumeableID_ ;
      public boolean hasConsumeableID() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getConsumeableID() {
        return consumeableID_;
      }
      public Builder setConsumeableID(int value) {
        bitField0_ |= 0x00000002;
        consumeableID_ = value;
        onChanged();
        return this;
      }
      public Builder clearConsumeableID() {
        bitField0_ = (bitField0_ & ~0x00000002);
        consumeableID_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 quantity = 3;
      private int quantity_ ;
      public boolean hasQuantity() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getQuantity() {
        return quantity_;
      }
      public Builder setQuantity(int value) {
        bitField0_ |= 0x00000004;
        quantity_ = value;
        onChanged();
        return this;
      }
      public Builder clearQuantity() {
        bitField0_ = (bitField0_ & ~0x00000004);
        quantity_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:proto.UserConsumablesProto)
    }
    
    static {
      defaultInstance = new UserConsumablesProto(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:proto.UserConsumablesProto)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_UserConsumablesProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_UserConsumablesProto_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032UserConsumablesProto.proto\022\005proto\"O\n\024U" +
      "serConsumablesProto\022\016\n\006userID\030\001 \001(\005\022\025\n\rc" +
      "onsumeableID\030\002 \001(\005\022\020\n\010quantity\030\003 \001(\005B.\n\034" +
      "com.lvl6.aoc2.noneventprotosB\016UserConsum" +
      "able"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_proto_UserConsumablesProto_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_proto_UserConsumablesProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_proto_UserConsumablesProto_descriptor,
              new java.lang.String[] { "UserID", "ConsumeableID", "Quantity", },
              com.lvl6.aoc2.noneventprotos.UserConsumable.UserConsumablesProto.class,
              com.lvl6.aoc2.noneventprotos.UserConsumable.UserConsumablesProto.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
